### ISSUE TITLE
Action Facade\Ignition\Http\Controllers\ShareReportController not defined. in Laravel 6.0

### ISSUE THREAD

**Issue by pavelforever** [facade/ignition#101]
I have updated Laravel from 5.8 to 6.0, then installed "ignition", added dummy error in Controller and got
 `Action Facade\Ignition\Http\Controllers\ShareReportController not defined`
![ignition](https://user-images.githubusercontent.com/9401132/64360730-b4ee8f80-d013-11e9-8c3e-8f8777919048.jpg)
![ro ru](https://user-images.githubusercontent.com/9401132/64360744-be77f780-d013-11e9-987e-a8709e549b6c.png)

**Comment by mpociot** [comment]
Have you cleared your route cache?

**Comment by pavelforever** [comment]
No, now I do and it works, thank you!

**Comment by mpociot** [comment]
Awesome! :)
