### ISSUE TITLE
Collapse vendor frames not working

### ISSUE THREAD

**Issue by emargareten** [facade/ignition#103]
Collapse vendor frames not working

**Comment by mpociot** [comment]
Can you provide some more information?
Which OS do you use? 
Which browser?
Do you see a JavaScript error?

**Comment by emargareten** [comment]
Windows 10
Chrome

I do see some 500 errors
in one application its for `_ignition/health-check`
in another its for the `ignition-code-editor` (which doesn't work either)

**Comment by emargareten** [comment]
The code editor doesn't work for syntax errors

**Comment by DarkStoorM** [comment]
Same here, Win10, Chrome / Firefox latest updates, no JS errors.
Just guessing here, could it be lodash not picking up the vendor frames correctly?
`return !t.relative_file.startsWith("vendor/") && "unknown" !== t.relative_file`
In the logs and in the debugger the path is separated by double backslash and the full path is returned for t.relative_path.
<details> 
  <summary>P.S.</summary>
   a pure shot in the dark, I don't know lodash 
</details>

**Comment by sebastiandedeyne** [comment]
So we should support detecting vendor frames by using `vendor\` instead, right?

**Comment by mpociot** [comment]
@sebastiandedeyne Yeah I think we should detect both.

**Comment by Surt** [comment]
@freekmurze on v1.11.2 I still can't collapse vendor frames.

**Comment by samerzaki** [comment]
I am facing the same problem and can't collapse vendor frames.

**Comment by sebastiandedeyne** [comment]
Do you see anything in your browser's console?

**Comment by samerzaki** [comment]
nothing appear in the browser, I still have the same problem
laravel 6.11
facade/ignition": "^1.16

**Comment by DarkStoorM** [comment]
I can confirm this function works on a live server and only breaks on a local machine, no errors whatsoever. I suppose it's a pathing problem.
