### ISSUE TITLE
Window/Viewport Control

### ISSUE THREAD

**Issue by horsesNhalo** [facade/ignition#111]
How do I control the window's aspect scale/position on the screen? How do I create a second Window and/or Viewport for a game instance without having a player spawned in. I just want more Viewport control. I've seen lots of mentions of Slate, but not any documentation explaining how to use it. I don't think UMG will meet my needs. Render Textures won't render particles so that will not work for me. I'm using UE4.22.3 and that version is locked by my school so I can't switch versions.

Thanks in advance for any information

**Comment by mpociot** [comment]
I don't think that issue is related to this repository :)

**Comment by horsesNhalo** [comment]
Where is the proper place to post this and get a useful response?
