### ISSUE TITLE
ViewException in fresh install

### ISSUE THREAD

**Issue by rikiless** [facade/ignition#114]
```
Facade\Ignition\Exceptions\ViewException Unable to locate Mix file: /css/web.css
```

I got this error when tried to change from Whoops to Ignition on Laravel 5.8 project. Also I got this error when installed fresh new Laravel 6 project via `laravel new` command.

PHP 7.2.2

**Comment by mpociot** [comment]
This exception is not related to Ignition, but to your own application. Did you run npm/yarn to generate the mix file that is missing?
The `web.css` file must be coming from your own application.

**Comment by rikiless** [comment]
Thank you. I will check this again.
