### ISSUE TITLE
ProposeFileChange Idea, show diff, or download patch to fix

### ISSUE THREAD

**Issue by MrRio** [facade/ignition#116]
Writing and playing around with fixers has highlighted that we’re perhaps missing something. We need some way to “Propose a file change”.

If env is set to local we can offer to make the file change for them, but if this is on a QA or staging server, ideally what you’d want is to see a diff, and download a patch. Kind of like how style-ci works. 

Just opening this as an issue initially to gather some feedback but happy to help implement.

**Comment by freekmurze** [comment]
Thank you for your suggestion. I'm thinking this functionality would below more in a third party package that adds a new tab for this.
