### ISSUE TITLE
dark theme doesn't follow dark theme basic guidelines

### ISSUE THREAD

**Issue by Gummibeer** [facade/ignition#118]
The little "hide solutions" link for example has a color contrast of [3.78](https://contrast-ratio.com/#%23d8d8df-on-%233F727D). But even the much more important tab bar has a crazy low value of [2.67](https://contrast-ratio.com/#%234b4b55-on-%238e8ea0) for the inactive tabs.

The color accents also shouldn't get darker but brighter and less saturated. 

**resources:**
* https://material.io/design/color/dark-theme.html
* https://medium.com/snapp-mobile/design-for-the-dark-theme-9a2185bbb1d5
* https://contrast-ratio.com

**Comment by freekmurze** [comment]
Closing for now, but we'll revisit this when creating a new major version.
