### ISSUE TITLE
Initial installation appears to break package-provided blade directives.

### ISSUE THREAD

**Issue by danmatthews** [facade/ignition#12]
I've installed the package on a laravel `5.8.34` app, and it appears to break blade directives in my views provided by:

`"spatie/laravel-permission": "^2.9",`
and 
`"lab404/laravel-impersonate": "^1.3",`

![Screenshot 2019-08-30 at 16 30 19](https://user-images.githubusercontent.com/149426/64033106-ac91e280-cb43-11e9-885d-60bfea81a152.png)
![Screenshot 2019-08-30 at 16 30 16](https://user-images.githubusercontent.com/149426/64033107-ac91e280-cb43-11e9-9074-627878b43366.png)

**Comment by danmatthews** [comment]
Looks to be caused by line 313 in `IgnitionServiceProvider.php`:

```
if (!$resolver->resolve('blade') instanceof LaravelCompilerEngine) {
            return false;
 }
```

Commenting this out fixes it for me.

**Comment by danmatthews** [comment]
Looks like an issue with automatic package loading maybe? The Blade Compiler class is replaced with your overridden version but at the time of execution, it hasn't registered all the custom tags from packages yet.

Moving it to `boot()` seems to fix it, but not sure if that'll conflict with the information you're collecting.

**Comment by mpociot** [comment]
Thanks for investigating @danmatthews 
Moving the view engine registration to the boot method is indeed the correct way to fix this. Data collection remains working there 👍
