### ISSUE TITLE
file_exists(): open_basedir restriction in effect. File(/home/runcloud/.ignition) is not within the allowed path(s):

### ISSUE THREAD

**Issue by kurumbus** [facade/ignition#120]
![2019-09-07_11h54_21](https://user-images.githubusercontent.com/13556916/64472445-3acf1f80-d167-11e9-9bef-2bef15c42dad.png)

I guess the bug is somehow environment-related but I have no idea what it's all about :-/
Locally it's fine.

Is it related to #27 and #90?

**Comment by freekmurze** [comment]
Could you check which version of the package you are running on production? If not the latest one, could you try to upgrade?
