### ISSUE TITLE
Precise error location

### ISSUE THREAD

**Issue by kylekatarnls** [facade/ignition#123]
Hi,

I maintain [laravel-pug](https://github.com/BKWLD/laravel-pug), a package to get pug views rendered in Laravel. The error mapping of Pug-php allow to know precisely where the error occurred: not just the line, but the offset start and end too (highlighted in blue on the screenshot below):
![image](https://user-images.githubusercontent.com/5966783/64489894-4bab8e00-d258-11e9-950d-74d71028ae63.png)

Would it be possible to tell (ideally using a method of [ViewException](https://github.com/facade/ignition/blob/master/src/Exceptions/ViewException.php)) that the error occurs between offsets X and Y (so the code between would be highlighted, or some cursor would appear in front of the first letter.

To go further: the start offset could be known while the end offset may be unknown in some situations, but it would be good enough, to say in this case to highlight until the end of the line or to highlight only the first character.

Thanks,

**Comment by freekmurze** [comment]
Since not that many users request support for this, we're not going to invest our time here.

If there is an easy fix, I'd accept a PR with tests for this.

Thanks!
