### ISSUE TITLE
Referer

### ISSUE THREAD

**Issue by bmichotte** [facade/ignition#124]
Hi there, could you add the [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) somewhere on the `Request` tab ?

It's sometimes usefull to know from where the page has been called

**Comment by freekmurze** [comment]
Will do!

**Comment by freekmurze** [comment]
Actually, we allready display all headers in the request tab. If there is a referer header it'll displayed in the "Headers" section of the Request tab.
