### ISSUE TITLE
Add session data to controlling collected data

### ISSUE THREAD

**Issue by sschlein** [facade/ignition#128]
It would be nice to remove the session information from the data that is sent to Flare like git information and SQL queries can be disabled:

https://flareapp.io/docs/ignition-for-laravel/controlling-collected-data

Session data might include all kinds of sensitive information.

**Comment by mpociot** [comment]
Do we want this as a custom configuration option, or should we make this a bit clearer in our documentation?
You can fully customize the data that we will send to Flare using a [custom middleware]().

To remove session data, you could register a custom middleware in one of your service providers like this:

```php
\Flare::registerMiddleware(function ($report, $next) {
    $context = $report->allContext();

    $context['session'] = null;

    $report->userProvidedContext($context);

    return $next($report);
});
```

I'm okay with adding this as a config option, but it might also be a good idea to clarify the middleware ability in our docs some more, so when someone wants to remove cookies, we don't have to add another flag.

**Comment by freekmurze** [comment]
Let's keep things simple and clearify it in our docs.

**Comment by mpociot** [comment]
Fixed this in the documentation
