### ISSUE TITLE
Suggestion: do not load external resources

### ISSUE THREAD

**Issue by duracellcell** [facade/ignition#134]
I hope I don't sound accusatory as english is not my main language.

I believe that it would be better for a development focused package to not load any external resources or make any unsolicited calls on the backend side. I have not reviewed the codebase but I assume that the latter is also true, as long as you don't define a Flare API key.

The external resource in question is the FontAwesome package:
https://github.com/facade/ignition/blob/107bc007da8268bffa6a6337294095ebc27ecb48/resources/views/errorPage.php#L22

Could you instead bundle this by default so no external connections are made? Since at least in my case the browser runs with very relaxed settings for local domains.

**Comment by joveice** [comment]
Would also like to see a end to external resources, I develop from a strict network and any css, images and such that are external will fail to load as it gets blocked.

**Comment by willemvb** [comment]
Good point! 
We are going to include the few Font Awesome icons we use as inline SVGs.
