### ISSUE TITLE
Why all the Flare stuff in this repo?

### ISSUE THREAD

**Issue by stancl** [facade/ignition#137]
There are some reasonable concerns about how Laravel is now too tied to Flare: https://www.reddit.com/r/laravel/comments/cya55q/ignition_and_flare_please_separate/

Why does this package publish Flare config, register the Flare client and depend on the Flare client?

It feels wrong from both an ethical and a code design perspective. From a code design perspective, Flare should depend on Ignition, not the other way around. From an ethical perspective, it's weird that the docs of Ignition, a part of Laravel, are on a third party SaaS's documentation site.

**Comment by mpociot** [comment]
Hi!

we built Ignition with the idea in mind to make it better through the use of Flare. The service is totally optional, we don't send/retrieve any information unless you explicitly use the "Share" button - which you can also disable if you don't want to see it at all.
Sharing errors with third parties becomes a lot easier and I think it's a great improvement to Ignition. It does not require any account and is completely free - so nobody forces you to do anything with Flare if you don't want to.

Technically we just built Flare first and use the report that we generate for Flare anyway, for the actual error page.

Regarding the documentation: We plan on splitting those up on a separate page - but if you rather want to see them on GitHub, they are here as well: https://github.com/facade/flare-docs
