### ISSUE TITLE
I get just a white/light screen with js errors in console

### ISSUE THREAD

**Issue by shemgp** [facade/ignition#138]
In Firefox: 

![Screenshot from 2019-09-12 14-26-29](https://user-images.githubusercontent.com/1734126/64759393-86b80500-d569-11e9-9b4e-5dc988144214.png)
In Chrome: ![Screenshot from 2019-09-12 14-26-35](https://user-images.githubusercontent.com/1734126/64759397-8a4b8c00-d569-11e9-8cad-d8b782f1f2e2.png)
Running this on Laravel 5.5 and here's the source: [🧨 View [hehe] not found.zip](https://github.com/facade/ignition/files/3604009/View.hehe.not.found.zip)

Thanks for the help.

**Comment by mpociot** [comment]
Do you know if there are any non-UTF8 characters in your views/session/cookies or anything like that?
Or maybe non-utf8 coming out of your database?

**Comment by joveice** [comment]
Not sure how much I can contribute. I have a error (connetion fails due to a call to external API fails). If I'm a guest everything works fine, if I sign in it fails. my username contains a "ø" which does get printed in the view. Hope it's at least somewhat helpful @mpociot

**Comment by mpociot** [comment]
Thank you! I just tagged 1.6.5 which fixes this issue!

**Comment by JayBizzle** [comment]
Can confirm my issue has been resolved with the latest release. Thanks!
