### ISSUE TITLE
Suggestion: Adds solution or Sharable links to JSON responses

### ISSUE THREAD

**Issue by peterfox** [facade/ignition#144]
I'm not really sure if this should be in here or the laravel/laravel repo but it seems to me that it could be possible to add a 'solution' key to JSON responses from Laravel applications that build out APIs. I was thinking it would be useful to have a error link key to get a shareable link from an API request.

I looked at adding it to my one of my own applications but it sadly didn't seem to work. Any ideas how this might be achieved?

**Comment by riasvdv** [comment]
This is not something that falls within the scope of Ignition
