### ISSUE TITLE
Postman API shows white screen

### ISSUE THREAD

**Issue by xitude** [facade/ignition#146]
When getting an error on postman api, the preview will only show a blank white screen.
The pretty view will have the markdown but in an unreadable way.

**Comment by mikeerickson** [comment]
+1

**Comment by Sn0wCrack** [comment]
Some kind of noscript view would be great for at least getting the basic exception in environments that can't run JavaScript

**Comment by mikeerickson** [comment]
Agreed, beats trying to figure out what is going wrong (of course reading the html quickly showed the issue)

**Comment by mpociot** [comment]
Version 1.6.9 now includes a noscript view of the error trace
![image](https://user-images.githubusercontent.com/804684/65150942-5d91eb80-da25-11e9-8915-cfd345797dfa.png)

**Comment by xitude** [comment]
Thanks for this @mpociot
