### ISSUE TITLE
Blank page since last update

### ISSUE THREAD

**Issue by Sindoweb** [facade/ignition#149]
It seems that barryvdh/laravel-debugbar v3.2.8 and ignition v1.6.7 are not playing along.

If Debugbar is installed I get a white screen (but the source code looks ok). If Debugbar is removed everything works fine.

There is a 'Uncaught SyntaxError: Unexpected token <' in _ignition/assets line 32.

**Comment by joveice** [comment]
I do not experience this with barryvdh/laravel-debugbar 3.2.7 and ignition 1.6.6

**Comment by Sindoweb** [comment]
It's weird - it worked as expected. 
Moved site to production server, did composer update and it just went blank on the first error.

**Comment by joveice** [comment]
@Sindoweb I hope you are not installing laravel-debugbar in production?

**Comment by mpociot** [comment]
@Sindoweb thanks for bringing that up. It's now fixed in 1.6.8
