### ISSUE TITLE
Ability to disable logging during runtime

### ISSUE THREAD

**Issue by Plytas** [facade/ignition#150]
There are cases where PHP reaches memory limit while working with big sets of data and database queries. [#29952](https://github.com/laravel/framework/issues/29952)

Would be nice to be able to disable/enable logging in these cases.

**Comment by mpskovvang** [comment]
I too experienced memory issues. The `flare.reporting.maximum_number_of_collected_queries` option solves some cases, but not all.

I accidentally posted my [original comment](https://github.com/laravel/framework/issues/29952#issuecomment-536948290) in the laravel/framework repository.

The suggestion of temporary disabling the logging of queries might be worth to consider.
