### ISSUE TITLE
Problems with route not found 404

### ISSUE THREAD

**Issue by eaglearg** [facade/ignition#156]
Hi,
I'm running laravel 6.0.3 with facade/ignition 1.7.0 but I have issues when an error is trying to show up in the browser, I don't know why but instead of trying to go to the correct route to reach the ignition controller it's cutting the route to localhost. My path is for example: 
http://localhost/nameofproject/public_html/home

I have an issue in that file and when is trying to render the ignition facade it's trying to access to:
http://localhost/_ignition/assets

In my .env I have the route setup
APP_URL=http://localhost/nameofproject/public_html/

Any ideas?

Thank you!

**Comment by mpociot** [comment]
This is now fixed in version 1.7.1
