### ISSUE TITLE
Disable AddGitInformation

### ISSUE THREAD

**Issue by bryanrscott** [facade/ignition#159]
Apologies if documented somewhere.   Is it possible to disable the AddGitInformation middleware in the ignition configuration file somehow?   I am getting timeouts on and not seeing the original error?

The process "git status -s" exceeded the timeout of 60 seconds.
..........
at AddGitInformation->isClean()

**Comment by mpociot** [comment]
Yeah you can disable this in the flare configuration file: https://flareapp.io/docs/ignition-for-laravel/controlling-collected-data#git-information

**Comment by bryanrscott** [comment]
Many thanks.
As additional note you must publish both config files ignition and flare.   The setting is in the flare configuration.   I had not setup the flare configuration as I had thought it was only if you where taking up the subscription service.
cheers
