### ISSUE TITLE
Conflict when accessing via BrowserSync

### ISSUE THREAD

**Issue by sebastiaanluca** [facade/ignition#16]
Tried out the package on an existing Laravel 5.8.34 project. When accessing via Laravel Mix's BrowserSync (http://localhost:3000), it produces a bunch of raw JavaScript instead of the error page. Works fine when accessing via the full local URL.

<img width="901" alt="Screenshot 2019-08-30 at 19 41 49" src="https://user-images.githubusercontent.com/711940/64040896-4ebec400-cb5e-11e9-9012-77152aafc5f9.png">

<img width="696" alt="Screenshot 2019-08-30 at 19 43 28" src="https://user-images.githubusercontent.com/711940/64040956-73b33700-cb5e-11e9-91d7-27be0a49999d.png">

**Comment by rdelafuente** [comment]
Hey!

This issue can be easily fixed if you change the _default_ match rule in your project's `webpack.mix.js` to inject BrowserSync just before closing the `</body>`.

https://www.browsersync.io/docs/options#option-snippetOptions

```js
mix.browserSync({
  snippetOptions: {
    rule: {
      match: /<\/body>/i,
      fn: function (snippet, match) {
        return snippet + match;
      }
    }
  }
});
```

**Comment by stevethomas** [comment]
ah my bad, thanks this resolved the issue.

**Comment by sebastiaanluca** [comment]
Any chance of this workaround/fix being implemented in Ignition itself or is it a BrowserSync thing?

**Comment by mpociot** [comment]
@sebastiandedeyne do you think we can solve this on our end?
Our inline javascript has a section that looks like this: 

```
return"<pre"+o.renderAttrs(a)+"><code>"+i(t[e].content)+"</code></pre>
```

Because of those HTML tags browsersync tries to inject it's custom JS - thus breaking ours.

**Comment by sebastiandedeyne** [comment]
Hmm I don't immediately see a solution on our end.

I also have 0 BrowserSync experience, if someone more with more knowledge of the topic could step in that would be great…

Until then, maybe we should property document the solution?

**Comment by OwenMelbz** [comment]
I think this should be resolved within Ignition itself.

As 2 "official" Laravel provided packages, that are not directly compatible with each other, it offers a pretty bad experience, both Mix and Ignition ship together, yet if you turn an option on within Mix it breaks Ignition. You can see how this would be considered pretty bad experience for developers, especially as one of the greatest appealing features of Laravel is a positive developer one.

The problem that users face is almost impossible to identify without some luck, there is no indication why it's suddenly spewing code around, let alone a link between browser sync and ignition.

I'm not saying this is a trivial fix, it's probably going to be very complicated - but if the quality and compatibility of these Laravel packages take a downward spiral and things like this get ignored, it's going to reflect badly on the whole Laravel Ecosystem. It reminds me of the fact you cannot plugin an iPhone to a Macbook without buying additional peripherals.

Hopefully some great minds can bash together and solve another problem!

**Comment by mpociot** [comment]
This is now fixed in version 1.6.7 👍

**Comment by OwenMelbz** [comment]
@mpociot You sir, are a true gent! 

![party time](https://media.giphy.com/media/3KC2jD2QcBOSc/giphy.gif)

**Comment by fitztrev** [comment]
I know this has already been resolved, but I have an open PR with laravel-mix (https://github.com/JeffreyWay/laravel-mix/pull/2227) that fixes the regex match on their side too.

**Comment by mpociot** [comment]
Given the unwanted side effects in #161 it might be best to have this solved in laravel-mix instead.

**Comment by mpociot** [comment]
I had to revert the change as this led to Ignition not being usable in certain situations. So this needs to be fixed on Laravel Mix instead.

**Comment by vikas5914** [comment]
How about publish the js files to vendor folder ?

**Comment by freekmurze** [comment]
This will be fixed by https://github.com/JeffreyWay/laravel-mix/pull/2227

**Comment by kvlknctk** [comment]
> Hey!
> 
> This issue can be easily fixed if you change the _default_ match rule in your project's `webpack.mix.js` to inject BrowserSync just before the close of the `</body>` tag. This will prevent BrowserSync to mess Ignition's startup
> 
> https://www.browsersync.io/docs/options#option-snippetOptions
> 
> ```js
> mix.browserSync({
>   snippetOptions: {
>     rule: {
>       match: /<\/body>/i,
>       fn: function (snippet, match) {
>         return snippet + match;
>       }
>     }
>   }
> });
> ```

It's a perfect match.
