### ISSUE TITLE
Error not being rendered when there is a syntax error on web.php

### ISSUE THREAD

**Issue by aglipanci** [facade/ignition#161]
Version: 1.8.0
Laravel: 6.0

If there is a syntax error in the route web.php the error page will not render. I think it's related to the fact that _ignition/assets are served as a route. Just a blank screen is returned.

**Comment by ceejayoz** [comment]
Same issue here if I trigger an exception in `app/Providers/AppServiceProvider.php`. White screen because the assets themselves are subject to that exception.

The assets probably need to be served as static files.

**Comment by mpociot** [comment]
Seems like the browsersync fix (#16) introduced this issue.
