### ISSUE TITLE
Target class [config] does not exist

### ISSUE THREAD

**Issue by hulkur** [facade/ignition#162]
PHP: 7.3.9
Laravel: 6.0.3
Ignite: 1.8.2

Error comes up in `IgnitionServiceProvider::register()` on calls to `config()`

Error is removed if comment out following lines:

In `registerDumpCollector()`:
246: `$dumpCollector = $this->app->make(DumpRecorder::class)->register();`
250: `$this->app->instance(DumpRecorder::class, $dumpCollector);`

In `registerBuiltInMiddleware()`:
281: `AddDumps::class,`

It appears that the problem is somehow related to `DumpRecorder` as AddDumps also requires it in constructor.

**Comment by hulkur** [comment]
If I apply fix for #131, then next error coms from 
100: `$this->app->get('flare.client')`

**Comment by hulkur** [comment]
Fixed.

I had overridden `Application::registerCoreContainerAliases` and in there you should replace
`self::class` in
`'app' => [self::class, \Illuminate\Contracts\Container\Container::class, \Illuminate\Contracts\Foundation\Application::class, \Psr\Container\ContainerInterface::class],`
with full name of parent class

Still don't understand how that is problem now but worked before.

**Comment by ivansushchyk** [comment]
Guys , i resolve this problem using Tests\TestCase instead of default LaravelTestCase
