### ISSUE TITLE
Remove select-none class on exception message

### ISSUE THREAD

**Issue by felixpenrose** [facade/ignition#163]
![image](https://user-images.githubusercontent.com/19385799/65340887-14799d00-dbc7-11e9-9a18-686beaf238ae.png)

The main error message is given a class of `select-none` meaning we can't copy this error and google an answer easily.

What benefit is there to doing this? Can this be removed or toggled off?

Laravel 6.0.3
ignition 1.8.2

**Comment by nathanheffley** [comment]
Unfortunately, this isn't as easy as removing the class, because of the click event if you try to highlight the entire message, unless you're careful about where you release your click, it will minimize/expand the full message and unselect the text.

**Comment by felixpenrose** [comment]
I see a similar issue with some sites that force a "select all" for a snippet of code when you only want to select a small part of the snippet. Instead of being able to click, drag and release to select the code you want, the JS behind the scenes selects everything regardless.

This is however relatively easy to bypass;
Click, drag the text you want. While still holding the mouse down press <kbd>Ctrl</kbd>+<kbd>C</kbd> and you're good to go.

The same solution could be used to allow a copy of the error string here.

However this still leaves the bigger issue that you cannot copy the error string easily. I'd argue that clicking the entire error string to trigger the drop down is not good UX. A dedicated button to perform this action makes more sense IMO.

The fact you *can* select text if the error only spans a single line is also a little inconsistent.

**Comment by willemvb** [comment]
Thanks for your input! This is indeed not right and in fact a remainder of some ported code from Flare where error cards are shown in list views as well.
Will be updated with #165

**Comment by felixpenrose** [comment]
Thanks for the super fast fix on this. Keep up the good work 😀
