### ISSUE TITLE
Use of deprecated way for shell process instantiation in AddGitInformation middleware

### ISSUE THREAD

**Issue by golonix** [facade/ignition#173]
Symfony's `Process` class used for adding GIT information (`AddGitInformation` middleware) has this piece of code:
```
    if (!\is_array($command)) {
        @trigger_error(sprintf('Passing a command as string when creating a "%s" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.', __CLASS__), E_USER_DEPRECATED);
    }
```
As you can see, it triggers an error when command used during `Process` instantiation (new `Process(...)`) is a string. Because the error is suppressed, nothing will break, however defining command as a string is deprecated.

There is a simple fix for that which I'm happy to contribute.

Regards

**Comment by freekmurze** [comment]
We'll continue this in #174
