### ISSUE TITLE
Poorly designed IgnitionServiceProvider

### ISSUE THREAD

**Issue by schursin** [facade/ignition#177]
https://laravel.com/docs/5.8/providers#the-register-method

> As mentioned previously, within the register method, you should only bind things into the service container. You should never attempt to register any event listeners, routes, or any other piece of functionality within the register method. Otherwise, you may accidentally use a service that is provided by a service provider which has not loaded yet.

But in `IgnitionServiceProvider::register()` we have `Log::extend()`, `Route::get()` and etc. As a result, errors occur (facades has wrong instances) when replacing an implementation such as, for example, `LogManager`.

Please move this code to `boot()` method.

**Comment by schursin** [comment]
@taylorotwell big problem here :(

**Comment by freekmurze** [comment]
Thanks for bringing this to our attention. We'll fix this today.

**Comment by mpociot** [comment]
This is now fixed in 1.9.2
