### ISSUE TITLE
Slow "Class Not Found" Errors

### ISSUE THREAD

**Issue by king724** [facade/ignition#179]
I am seeing super slow response times for a "Class Not Found" error.

Valet it takes ~3 seconds.
With my Docker env ~8 seconds.

To reproduce, install a fresh copy of Laravel 6.1 and this route:
```
Route::get('/', function () {
    $x = new Carbon\Carbbon();
});
```

**Comment by king724** [comment]
I found a solution to the problem.

First, publish the Ignition config file and then ignore these two solution providers.

```
'ignored_solution_providers' => [
    Facade\Ignition\SolutionProviders\MissingPackageSolutionProvider::class,
    Facade\Ignition\SolutionProviders\MissingImportSolutionProvider::class,
],
```

Valet went from 3000ms to 300ms by disabling the `MissingPackageSolutionProvider` provider as it does a file_get_contents on up to 16 Packagist API calls (1 for the search and up to 15 package detail calls).

Went from 300ms to 95ms by disabling the `MissingImportSolutionProvider` as it looks like it scans a bunch of files/folders in your vendor directory. So if you have a lot of require packages, this timing goes up.

Second, publish the Flare config file (even though I had no intention of using Flare!) and set `'collect_git_information'` to false. This drops the 95ms to 35ms.

`Class Not Found` errors
Valet: before config updates: 3000ms; post config updates: 35ms.
Docker: before config updates: 8000ms; post config updates: 80ms.


Does anyone know of a way to completely disable Flare from a fresh install of Laravel 6? 

Also, I feel like some, if not all, of these Solution providers should be opt-in instead of opt-out.

**Comment by mpociot** [comment]
Thank you for the time you’ve put into investigating this issue. 

Regarding your question: Flare is not enabled - and we don’t receive any information by default. We make use of the report that we would need for Flare and give it to the local Ignition page. 
That’s why disabling he git information removes them from Ignition. 
But just to clarify: Flare is not enabled by default or anything - that’s all Ignition. 

I will look into adding some strict timeout rules to these calls - and it might be worth thinking about having the Packagist Solution as an opt-in.

**Comment by king724** [comment]
Thanks @mpociot! I appreciate the work you and @freekmurze have put into this project!

**Comment by Matthijsvdorp** [comment]
Can confirm: Disabling `collect_git_information` in the flare config file reduced my loading times for an error page from ~20seconds to ~500ms. 

For reference, this command creates the flare config file php artisan vendor:publish --provider="Facade\Ignition\IgnitionServiceProvider" --tag="flare-config"

**Comment by wyred** [comment]
I recently upgraded my app to Laravel 6.x with Ignition. This is a fairly large app with 4900+ commits and it takes 30 seconds to render the ignition error page with default config.

Adding all the solution providers to `ignored_solution_providers` reduces it to 10 seconds. Subsequent refresh is at 2.5 seconds.

Publishing the flare config in order to disable `collect_git_information` finally brings it back to milliseconds.

It's kind of weird that even though I don't use Flare, I have to publish its config in order to disable a setting to improve the speed.

**Comment by pablood85** [comment]
It's so frustrating I ended up setting debug=false.
I'm using windows + homestead
:(

**Comment by vedmant** [comment]
I had the same problem, collect_git_information fixed the issue. This package looks quite raw that just usual Class not found error causes so much issues and required configs tweaks.

**Comment by Yelfive** [comment]
I found it tries to ”getSolution”, and takes 50s at `\Facade\Ignition\Support\Packagist\Package::getNamespaces` trying to get possible package information. Is there a switch I can turn this feature off ?  If I really want same package, I will find it myself, not this way...

**Comment by Yelfive** [comment]
Found the solution to my problem by going through the code, there's a config related to this

inside `config/ignition.php`

```php
    'ignored_solution_providers' => [
        Facade\Ignition\SolutionProviders\MissingPackageSolutionProvider::class,
    ],
```

here's a full list for `defaultSolutions`

```php
    'ignored_solution_providers' => [
        Facade\Ignition\SolutionProviders\IncorrectValetDbCredentialsSolutionProvider::class,
        Facade\Ignition\SolutionProviders\MissingAppKeySolutionProvider::class,
        Facade\Ignition\SolutionProviders\DefaultDbNameSolutionProvider::class,
        Facade\Ignition\SolutionProviders\BadMethodCallSolutionProvider::class,
        Facade\Ignition\SolutionProviders\TableNotFoundSolutionProvider::class,
        Facade\Ignition\SolutionProviders\MissingImportSolutionProvider::class,
        Facade\Ignition\SolutionProviders\MissingPackageSolutionProvider::class,
        Facade\Ignition\SolutionProviders\InvalidRouteActionSolutionProvider::class,
        Facade\Ignition\SolutionProviders\ViewNotFoundSolutionProvider::class,
        Facade\Ignition\SolutionProviders\UndefinedVariableSolutionProvider::class,
        Facade\Ignition\SolutionProviders\MergeConflictSolutionProvider::class,
        Facade\Ignition\SolutionProviders\RunningLaravelDuskInProductionProvider::class,
        Facade\Ignition\SolutionProviders\MissingColumnSolutionProvider::class,
        Facade\Ignition\SolutionProviders\UnknownValidationSolutionProvider::class,
    ],
```

**Comment by eckelarsson** [comment]
> I found a solution to the problem.
> 
> 1. First, publish the Ignition config file and then ignore these two solution providers.
> 
> ```
> 'ignored_solution_providers' => [
>     Facade\Ignition\SolutionProviders\MissingPackageSolutionProvider::class,
>     Facade\Ignition\SolutionProviders\MissingImportSolutionProvider::class,
> ],
> ```
> 
> Valet page load times went from 3000ms to 300ms by disabling the `MissingPackageSolutionProvider` provider as it does a file_get_contents on up to 16 Packagist API calls (1 for the search and up to 15 package detail calls).
> 
> Valet page load times went from 300ms to 95ms by disabling the `MissingImportSolutionProvider` as it looks like it scans a bunch of files/folders in your vendor directory. So if you have a lot of required packages, this timing goes up.
> 
> 1. Second, publish the Flare config file (even though I had no intention of using Flare!) and set `'collect_git_information'` to false. This drops the 95ms to 35ms.
> 
> #### Summary
> Valet page load: before config updates: 3000ms; post config updates: 35ms.
> Docker page load: before config updates: 8000ms; post config updates: 80ms.
> 
> #### Questions
> Does anyone know of a way to completely disable Flare from a fresh install of Laravel 6?
> 
> Also, I feel like some, if not all, of these Solution providers should be opt-in instead of opt-out.

This worked for me running och a docker container locally.

**Comment by gpressutto5** [comment]
It's really a shame we need to add a flare config file to the project even though we have no intention of using Flare. I know 2.0 fixed this, but the latest LTS Laravel version is 6.0, which is not supported by 2.0.

**Comment by freekmurze** [comment]
In v1 the ` Facade\Ignition\SolutionProviders\MissingPackageSolutionProvider::class` is added to the default `ignored_solution_providers` value, effectively solving this issue.
