### ISSUE TITLE
SplFileInfo::getSize(): stat failed for C:\Windows\Temp\

### ISSUE THREAD

**Issue by jagDanJu** [facade/ignition#180]
Hey Guys,

I have updated my Laravel app from 5.8 to 6 and installed this package.
If I now upload a file via a form and use the command "ddd", the following error appears:

![image](https://user-images.githubusercontent.com/3613218/66256725-2f383e00-e791-11e9-84ec-ed75b69cd816.png)

**Comment by mpociot** [comment]
This is now fixed in the underlying `facade/flare-client-php` package version 1.1.1.

Please perform a composer update to pull in the latest version.
