### ISSUE TITLE
"Target class [config] does not exist" exception when using dump()

### ISSUE THREAD

**Issue by gdebrauwer** [facade/ignition#181]
PHP: 7.3.6
Laravel: 6.1.0
Ignition: 1.9.2

## What is bug?

When you use the dump() function inside the code of a project, an exception is throw if you run the tests of that project:

```
1) Tests\Feature\ExampleTest::testBasicTest
Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist.

/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:806
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:682
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:630
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:768
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:121
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:283
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:286
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:192
/Users/myusername/Documents/myproject/app/Exceptions/Handler.php:49
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:326
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:120
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:434
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:224
/Users/myusername/Documents/myproject/tests/Feature/ExampleTest.php:17

Caused by
ReflectionException: Class config does not exist

/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:682
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php:630
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:768
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:121
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:283
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:286
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:192
/Users/myusername/Documents/myproject/app/Exceptions/Handler.php:49
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:326
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:120
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:434
/Users/myusername/Documents/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:224
/Users/myusername/Documents/myproject/tests/Feature/ExampleTest.php:17
```

## How to reproduce?

1. Create a new laravel project
2. Add a dump() to the '/' route
3. Run the default tests
4. `Target class [config] does not exist` exception thrown.
_If you uninstall `facade/ignition`, the tests will work again._

**Comment by hulkur** [comment]
It starts with `Target class [view] does not exist` and follows by multiple `Target class [config] does not exist`

**Comment by ionutantohi** [comment]
It seems to be related to how laravel is booted before each test. This bug manifests only when you run a suite with multiple tests and you dump in second test executed by phpunit. If tests are executed individually one at the time it work fine.

Example:
```

**Comment by ionutantohi** [comment]
It seems to be related to how laravel is booted before each test. This bug manifests only when you run a suite with multiple tests and you dump in second test executed by phpunit. If tests are executed individually one at the time it work fine.

Example:

Run: `vendor/bin/phpunit --filter=DumpTest` 

```php
<?php

namespace Tests\Unit;

use Tests\TestCase;

class DumpTest extends TestCase
{
    public function test_1()
    {
        $this->assertTrue(true);
    }

    public function test_2()
    {
        dump('something');

        echo get_class(app('db'));

        $this->assertTrue(true);
    }
}
```

If the whole suite is executed, it breaks. If test_2 is executed individually it works. 

@mfn did some debugging in the issue posted in laravel/framework repo and said the following

> It works for me if I do the following: composer remove --dev facade/ignition
> 
> How I came to this:
> 
> -  when I debugged it, I realized that \Symfony\Component\VarDumper\VarDumper::$handler was already set
> -  it had a closure reference to facade/ignition

@freekmurze @mpociot

**Comment by austenc** [comment]
Also running into this, it's a frustrating one to debug! If we disable `flare.send_logs_as_events` in config, the issue does not occur. Tried following this down the chain and it seems to be related to the following line in the flare php client:

https://github.com/facade/flare-client-php/blob/master/src/Truncation/ReportTrimmer.php#L29

Encountered this when we had a test with a `setUp` method like this:
```
    public function setUp(): void
    {
        parent::setUp();
        config(['logging.default' => 'stack']);
    }
```
We were writing a custom log handler to write activity logs to a database table. The intent was to test that our log handler was working correctly in the context of the overall log stack, which is when we ran into this error. It seems that with some payloads, the json encoding has a problem because it is outside of the app's main context? Wish I were able to post more (helpful) code, but in this case the error seems so many layers deep that it would be counterproductive to litter the issue with unhelpful code.

#236 brings up a good point though. Why is Flare / Ignition trying to run in the testing environment? Although our test explicitly set the logging default to `stack` it still seems odd that flare would be running given the environment (a phpunit test). Happy to help debug this further if someone who knows more about ignition/flare and what it does with the application context wants to chime in!

**Comment by hartbit** [comment]
Same problem here.

**Comment by jallowmamadou** [comment]
I know this is an old thread but incase someone else face this issue. In my case MyTest.php  was extending PHPUnit TestCase instead of Tests\TestCase. This fixed it for me.

**Comment by othyn** [comment]
As above, an old thread, but wanted to post my fix. This took an embarrasingly long amount of time to debug...

My error was `Target class [import] does not exist.`, but this was the closest issue I could find to the actualy problem searching online.

For me it was a custom route middleware declaration that I had accidentally overwritten as part of an upgrade from Laravel 6 to 7.

**Comment by freekmurze** [comment]
Reading though this thread, I think this error was not caused by Ignition itself.

If you are experiencing this error, open up a new issue.

**Comment by patriziotomato** [comment]
Would recommend to check your Base Test class (or setUp()) or similar pre-processing locations. In my case I changed

```php
app('config')->set(...);
```

to

```php
$this->app->make('config')->set(...);
```

Did not debug the cause honestly, but look out for similar things in this case...

**Comment by afsanajamal** [comment]
Same Problem here

**Comment by Arkhas** [comment]
for those of you still having this issue, the solution for me was the following : 

https://www.thisprogrammingthing.com/2020/Fixing-the-Target-class-config-does-not-exist-Error/

>The issue was that I had forgotten to include parent::setup() in the test class’ setup() function.

**Comment by goper-leo** [comment]
I solved this by extending the proper `TestCase` file. On your test file 
**use** 
`use Tests\TestCase;` 
not
`use PHPUnit\Framework\TestCase;`
ex:
```
<?php

namespace Tests\Feature\Scraper;

use Tests\TestCase;
use App\Models\WebPage;

class HtmlParserTest extends TestCase
{
    public function testExample()
    {
        $this->assertTrue(true);
    }
}
```
