### ISSUE TITLE
error page is not displayed in IE

### ISSUE THREAD

**Issue by jagDanJu** [facade/ignition#186]
the error page looks good in ff or chrome, but not in IE
The following errors are shown in the console:

![image](https://user-images.githubusercontent.com/3613218/66346154-d49a1000-e951-11e9-937d-afd7a09c60ef.png)

"syntaxerror"
"The object doesn't support this property or method"
"Ignition is undefined"

**Comment by AdrianMrn** [comment]
This happens because we're compiling Ignition for ES6, which IE11 doesn't have support for. I'll have a look if we can easily change the babel and/or webpack config to output to ES5.

**Comment by jagDanJu** [comment]
somethin new here? @AdrianMrn @sebastiandedeyne

**Comment by jagDanJu** [comment]
@AdrianMrn @sebastiandedeyne @freekmurze Anything new?

**Comment by freekmurze** [comment]
We assume that developers use a more modern browser than IE11. Regular users should never see the ignition page.
