### ISSUE TITLE
proc_open error on laravel 6

### ISSUE THREAD

**Issue by MrKappa** [facade/ignition#188]
Hi,

I want to point your attention to [this issue on laravel 6](https://github.com/laravel/framework/issues/30054). A proc_open is called for adding git informations and this prevents installing laravel 6 on a webserver without proc_open enabled. 
I think it would be better if this feature doesn't depend on proc_open if possible.

**Comment by moosapour-arash** [comment]
i think it should let the users to disable this feature in config files

**Comment by freekmurze** [comment]
This can be solved by setting `collect_git_information` in the `flare` config file to `false`.
