### ISSUE TITLE
disable reporting of specific error types

### ISSUE THREAD

**Issue by robtesch** [facade/ignition#189]
Hi there, thanks for this great package. We are now subscribing flare users, but would love a way to prevent the reporting of specific errors. Having used similar solutions in the past, all of them provided some way of ignoring specific error types, and if this exists in this package i haven't found it yet.

In our case, we do not want to report `League\OAuth2\Server\Exception\OAuthServerException`

Is there anything on the roadmap to do this, or is there perhaps some hack we could chuck in for now? Perhaps in a service provider or similar?

**Comment by freekmurze** [comment]
That's a great suggestion, we'll look into this soon.

**Comment by robtesch** [comment]
@freekmurze many thanks!

**Comment by freekmurze** [comment]
For now you can already add your exception class to the `dontReport` property of `App\Exceptions\Handler`. We'll soon make it possible to have more fine grained control over which errors are being sent to Flare.

**Comment by robtesch** [comment]
Ah, fantastic, yes, that will work. Looking forward to a first class solution going forward.

**Comment by freekmurze** [comment]
I'm going to close this for now, but I'll take a look again when we create a new major version of the package.
