### ISSUE TITLE
Errors before bootstrapping finishes are not displayed

### ISSUE THREAD

**Issue by jasonvarga** [facade/ignition#192]
1.9.2 introduced a bug where some fatal errors are not displayed, instead you get `Action Facade\Ignition\Http\Controllers\ShareReportController not defined.` 1.9.1 was working fine.

For example, a syntax error like an extra semicolon or random unexpected character. You should see `syntax error, unexpected '}'`

Or if you define an abstract method but don't implement it. You should see `Class Foo contains 1 abstract method ...`

**Comment by freekmurze** [comment]
Also reported in #202 

This will be fixed soon.

Thanks for reporting!
