### ISSUE TITLE
Not working in versions < 5.7

### ISSUE THREAD

**Issue by conroyp** [facade/ignition#20]
* Laravel Version: 5.5.48, 5.6.39

### Description:
In the documentation, support is mentioned for versions >= 5.5:

```
In Laravel 5.5, 5.6, 5.7 and 5.8 you can pull in the package via Composer:
```

After adding the package and setting the handler, in versions < 5.7 when an error is generated, the attempt to generate the `ShareReportController` url fails. This causes the old-style whoops page to still be generated.

The error comes from `Illuminate\Routing\UrlGenerator@formatAction`, and is:
```
strpos() expects parameter 1 to be string, array given
```

This is initially triggered by https://github.com/facade/ignition/blob/master/src/ErrorPage/ErrorPageViewModel.php#L99
```
protected function shareEndpoint()
{
    return action([ShareReportController::class]);
}
```

It looks like it's relying on code introduced by https://github.com/laravel/framework/pull/24738, but it seems that was only introduced at 5.7 (confusion about differing versions in documentation has been cleared up previously - https://github.com/laravel/framework/issues/24770)

Updating L99 in `ErrorPageViewModel` to the nastier-looking `return action(['\Facade\Ignition\Http\Controllers\ShareReportController']);` does allow the share url (`/flare/share-report`) to be generated when the changes from https://github.com/laravel/framework/pull/24738 are manually applied, so it seems related to that specific PR.

### Steps To Reproduce:
1. Inside a fresh Laravel project with either `5.5*` or `5.6.*` set as version numbers, and run `composer require --dev facade/ignition`

2. Paste the following code into `routes/web.php`:
```
Route::get('/error', function() {
    I_AM_BROKEN_CODE
});
```

3. Visit `http://{YOUR_PROJECT_URL}/error`

**Comment by freekmurze** [comment]
This is fixed via #21
