### ISSUE TITLE
ddd() function no params

### ISSUE THREAD

**Issue by cxlblm** [facade/ignition#203]
Ignition Version: 1.11.2

![TIM图片20191015150538](https://user-images.githubusercontent.com/17900096/66808226-64951680-ef5d-11e9-8035-882d09c9c254.png)

Symfony dump() function must have a parameter, but we use call_user_func_array() function not pass paramerts. Should we add a judgment for zero parameters?

**Comment by freekmurze** [comment]
I think it's find if it fails if you don't pass it any parameters. But the exception message is confusing. We'll fix that soon.

**Comment by cxlblm** [comment]
> I think it's find if it fails if you don't pass it any parameters. But the exception message is confusing. We'll fix that soon.

thanks!!!
