### ISSUE TITLE
Show only application code on stack trace.

### ISSUE THREAD

**Issue by Surt** [facade/ignition#209]
Is it possible to hide all the code related to vendor on the stack trace left column? 
On Whoops there were a tab to show the application execution without seen vendor libraries. On inginition I can see "collapse vendor frames" but it's doing nothing usefull to filter that information.

**Comment by samerzaki** [comment]
I have the same problem and though to back to whoops package

**Comment by freekmurze** [comment]
The vendor frames should be collapsed by default.

If they are not please open up a new PR with a screenshot and mentioning the OS / Browser versions you are using.
