### ISSUE TITLE
Undefined variable: Laravel 6

### ISSUE THREAD

**Issue by Toufikforu** [facade/ignition#211]
![01](https://user-images.githubusercontent.com/38946314/67341671-15994380-f552-11e9-9182-65de2f141799.png)
![02](https://user-images.githubusercontent.com/38946314/67341673-15994380-f552-11e9-8939-c83a1dd6dccb.png)
![003](https://user-images.githubusercontent.com/38946314/67341725-32ce1200-f552-11e9-84ea-faf5dbda5abb.png)

Please help me to solve this error.
**Controller:**
		$employees = Employee::all()->toArray();
		return view ('adminboard.employee.application',compact('Employee'));

**Blade file:**
@foreach($employee as $row)
<tr>
	<th scope="row">3</th>
	<td>{{$row['first_name']}}</td>
	<td>toufik@gmail.com</td>
	<td>123456789</td>
	<td><button class="btn-btn-warning">View</button></td>
</tr>	
@endforeach

**Comment by eaglearg** [comment]
> ![01](https://user-images.githubusercontent.com/38946314/67341671-15994380-f552-11e9-9182-65de2f141799.png)
> ![02](https://user-images.githubusercontent.com/38946314/67341673-15994380-f552-11e9-8939-c83a1dd6dccb.png)
> ![003](https://user-images.githubusercontent.com/38946314/67341725-32ce1200-f552-11e9-84ea-faf5dbda5abb.png)
> 
> Please help me to solve this error.
> **Controller:**
> $employees = Employee::all()->toArray();
> return view ('adminboard.employee.application',compact('Employee'));
> 
> **Blade file:**
> @foreach($employee as $row)
> 
> 3 {{$row['first_name']}} toufik@gmail.com 123456789 View @Endforeach
Hi. Toufikforu,
Well to start this is not the place to put this kind of question. You should try in https://laracasts.com/. But just looking at it, you named in the controller the variable "employees" and you're trying to access in the view with the name "employee". Just change the name in the view to "employees" and it should work

**Comment by Toufikforu** [comment]
I solved this. Thanks
