### ISSUE TITLE
How to manually load ignition at runtime?

### ISSUE THREAD

**Issue by mintymatt** [facade/ignition#217]
I'm looking to disable Ignition based upon the IP address of whoever is viewing the Laravel application.

It appears the provider is automatically loaded, how can I prevent and extend this behaviour?

Many thanks <3

**Comment by mpociot** [comment]
You can manually disable the package auto-discovery by adding this to your composer.json file:

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "ignition/facade"
        ]
    }
}
```

Then you have full control over when/how you want to load the service provider.
