### ISSUE TITLE
Possibility to show compiled Blade with error

### ISSUE THREAD

**Issue by Dimonka2** [facade/ignition#218]
Hi, just got a blade rendering exception 
> syntax error, unexpected ')'

And the the blade code looks pretty correct for me. The compiling is stopping on a custom blade directive. It would be really useful to see additionally to the "normal" blade a compiled version of it to understand where the issue is really coming from. I think old "Woops" (or what was the name of it?) showed only compiled version.
This is more like a feature request..
Thanks!

**Comment by sschlein** [comment]
Can you please check if this still happens with the latest Ignition package? This should be solved since 1.12.1

**Comment by Dimonka2** [comment]
Hi, probably I was not very clear in the initial question. 
The idea was to have a 2 possibilities to view a blade in the "stack trace" view:
1. option the blade itself, how it is saved in the filesystem
2. option a compiled version of the blade, how the Laravel "sees" it.

The "Woops" had only 2nd option and Ignition has only 1st one. it would be really cool to have both..

**Comment by keithbrink** [comment]
Adding a vote for this, as the Ignition error does not show the results of blade components, so if there is an issue in that component, it makes it hard to diagnose.

**Comment by tobyzerner** [comment]
Just ran into this as well. Had to manually go into my storage/framework/views directory and analyse the compiled code from there. Would be nice to be able to see directly on the error page 👍

**Comment by zarunet** [comment]
Just ran into this with 2.x, Ignition reported an error at line 90 of a 84-line view, which is really confusing. Either having the correct line or be able to see the compiled view would help with debugging.

**Comment by Petah** [comment]
Any progress on this?

**Comment by oott123** [comment]
Any progress on this?

**Comment by vike2000** [comment]
I don't know why this got closed w/o label or message but I solved it as follows.
I consider it too hacky to consider an as-is PR myself.
The repo maintainers could know better how to implement it more stable.

---
Possibly relevant versions in `composer.json`:
``` json
    "require": {
        "php": "^8.0",
        "laravel/framework": "^8.12",
    },
    "require-dev": {
        "facade/ignition": "^2.5",
    }
```

---
Most relevant follows.

---
Part of `composer.json`:
``` json
    "extra": {
        "laravel": {
            "dont-discover": [
                "facade/ignition"
            ]
        },
    },
```
I guess you have to run:
``` sh
composer dump-autoload
```

---
Part of `config/app.php`:
``` php
    'providers' => [
        // ...
        /* cause-of: (Facade\Ignition\Views\Engines\CompilerEngine
         *          extends \Illuminate\View\Engines\CompilerEngine)::handleViewException() {
         *              $this->modifyViewsInTrace(); } */
        env('IGNITION_DISABLE_VIEW_ENGINES')
            ? App\Providers\IgnitionServiceProvider::class
            : Facade\Ignition\IgnitionServiceProvider::class,
        // ...
    ]
```

---
Part of `.env`
``` env
IGNITION_DISABLE_VIEW_ENGINES=true
```

---
`app/Providers/IgnitionServiceProvider.php`:
``` php
<?php

namespace App\Providers;

use Facade\Ignition\IgnitionServiceProvider as FacadeIgnitionServiceProvider;

class IgnitionServiceProvider extends FacadeIgnitionServiceProvider
{
    protected function hasCustomViewEnginesRegistered()
    {
        /* I think logic is reversed as:
         * original is `if (! $resolver->resolve(…) instanceof Laravel…Engine)` `return false`
         * while top of registerViewEngines() `if (! $this->hasCustomViewEnginesRegistered())` `return $this` */
        return false;
    }
}
```

---

Hope I haven't forgotten anything and that it helps you as it does me (developing nested Directives or similarly complex Blade constructs).
Cheers,
vike
