### ISSUE TITLE
local_sites_path in config has no effect

### ISSUE THREAD

**Issue by plakhin** [facade/ignition#222]
`local_sites_path` config variable has no effect, `remote_sites_path` is always being used.
Was working fine some time ago, don't remember which version.

Current versions:
Laravel 6.6.0
facade/ignition 1.13.0
facade/ignition-contracts 1.0.0

**Comment by professorSchiggy** [comment]
Got the same issue. This is my config file:

![image](https://user-images.githubusercontent.com/57348983/70546830-43713080-1b70-11ea-9e18-31b885b90d0f.png)

And the link is still relative to my Homestead environment: 

![image](https://user-images.githubusercontent.com/57348983/70547206-cc886780-1b70-11ea-86dd-78b04c0e059d.png)

**Comment by Scott-DavidJones** [comment]
are you sure the filepath is exactly correct?

the code in question: editorUrl.js:
```javascript
file =
        (config.remoteSitesPath || false).length > 0 && (config.localSitesPath || false).length > 0
            ? file.replace(config.remoteSitesPath, config.localSitesPath)
            : file;
```

simply replaces remoteSitesPath with localSitesPath and if cannot replace it uses the default file path on the remote machine.

Noted on mine i had different case in my remote path compared to actual path:
remote: /home/vagrant/code/Mypath
actual: /home/vagrant/code/MyPath

Also i dont get an encoded url:
![image](https://user-images.githubusercontent.com/57994086/71670043-9cdf1080-2d66-11ea-85fb-2c7eb5e80759.png)

**Comment by freekmurze** [comment]
I'm thinking this should just work in the latest version. If not, please open a new issue.
