### ISSUE TITLE
Missing support to Symfony 5 / Laravel 7

### ISSUE THREAD

**Issue by nunomaduro** [facade/ignition#225]
Hey friends,

Do you have plans working on this soon?

**Comment by driesvints** [comment]
@nunomaduro https://github.com/facade/ignition/pull/239

**Comment by freekmurze** [comment]
You can already use `^2.0` in your `composer.json` file and it will pull in the current `v2` branch.

**Comment by nunomaduro** [comment]
Thanks @freekmurze @driesvints
