### ISSUE TITLE
A temporary file could not be opened..C:\Windows\TEMP\sf_proc..

### ISSUE THREAD

**Issue by jagDanJu** [facade/ignition#235]
Hey Guys,

I get the following error message at irregular intervals. 
I have to delete the specified file manually, then the correct error page is displayed.

Maybe that would be a solution?
https://github.com/symfony/symfony/issues/19336

![image](https://user-images.githubusercontent.com/3613218/71849526-8b816580-30d2-11ea-9ed4-832c15deca39.png)

Thx!
Daniel

**Comment by riasvdv** [comment]
This should be fixed in v2 as it's now using `symfony/process` v5
