### ISSUE TITLE
Disable Ignition during tests

### ISSUE THREAD

**Issue by tillkruss** [facade/ignition#236]
Ignition is producing a lot of unnecessary output when debugging unit tests.

Is there an easy way to just display the PHP error and stacktrace and disable Ignition when running PHPUnit?

**Comment by sakalauskas** [comment]
+ this. I am getting lots of irrelevant output in the unit tests in CI as well, e.g.:

```
  Error: Maximum function nesting level of '256' reached, aborting!
2068 /project/vendor/facade/ignition/src/DumpRecorder/MultiDumpHandler.php:10
2069 /project/vendor/facade/ignition/src/DumpRecorder/DumpRecorder.php:32
2070 /project/vendor/facade/ignition/src/DumpRecorder/MultiDumpHandler.php:13
2071 /project/vendor/facade/ignition/src/DumpRecorder/DumpRecorder.php:32
```

**Comment by calvincanas** [comment]
+this

assertSee and assertSeeText seems to be passing even when page returned 500 http code because Ignition displays the data from DB and binded to that view/page.

**Comment by austenc** [comment]
Also seeing strange output from this. 

All our tests are passing, but flare/ignition is spitting out some warnings after the tests stating that the `Config::get` facade method is undefined. It seems like ignition is doing something funny with the application context in tests. Digging around, but not sure where to look on this one 🤔

**Comment by simonschaufi** [comment]
I'm having an issue also with Behat tests since I run the tests in Gitlab Runner, I don't need to see a beautiful error output but would be happy with a whoops handler. In my case, I want to disable the package in certain environments to use the default error handler of Laravel.

**Comment by freekmurze** [comment]
I'd accept a PR that handles this.
