### ISSUE TITLE
Display actual exception class for ViewException

### ISSUE THREAD

**Issue by jasonvarga** [facade/ignition#237]
When a ViewException is thrown, naturally the error page says ViewException.

![image](https://user-images.githubusercontent.com/105211/72458100-f2b7ad80-3795-11ea-947c-690186273085.png)

Would it be possible to replace that with the actual exception?

Of course, we can look in the stack trace to see which exception was really thrown, but this could be more useful.

**Comment by freekmurze** [comment]
Which exception would you expect here?
