### ISSUE TITLE
Collapse vendor frames not working

### ISSUE THREAD

**Issue by samerzaki** [facade/ignition#241]
with the old package "Whoops" laravel used in Laravel 5.8, I could easily hide vendors frames and reach the real error in seconds to solve. but in Laravel 6 with ur package Ignition. the button Collapse vendor frames is not working and do nothing when clicked, and thus, the package has no benefit for me.
Os: windows
laravel version: 6.11
"facade/ignition": "^1.16",
-no errors in the browser console appear

**Comment by freekmurze** [comment]
I can't reproduce this error. If you are still experiencing this problem, please open up a new PR and also mention which browser + version you are using.
