### ISSUE TITLE
Error page runs git staus -s cauing timeout on homestead box

### ISSUE THREAD

**Issue by bsienn** [facade/ignition#245]
I'm running app in laravel homestead with virtualbox and vagrant. Whenever there is error for invalid route or if a class is missing etc, the error page runs `git status -s` causing the app to timeout. It does so because virtualbox is really slow on network communication and git command takes more than 2 minutes on vm.

1) What I really want to know is can I disable the git command on error page?
2) Could you please describe why the git command are needed and would I'll be missing something in case its disabled?

As there is no way to optimize virtualbox, I really do need a way to disable the git command.
heres a thread I made in laracast about this. [Link](https://laracasts.com/discuss/channels/laravel/homestead-server-times-out-when-route-not-found)

**Comment by anthonylee83** [comment]
I ran into this issue as well.  Have you had any luck getting around this?

**Comment by bsienn** [comment]
> 
> 
> I ran into this issue as well. Have you had any luck getting around this?

Hi, Yes, got some solution in an other [issue here](https://github.com/facade/ignition/issues/179). Follow the instruction given in comments.

**Comment by riasvdv** [comment]
Git information isn't collected by default anymore in v2
