### ISSUE TITLE
Non open source editor is default

### ISSUE THREAD

**Issue by DanAlexson90** [facade/ignition#247]
```
    /*
    |--------------------------------------------------------------------------
    | Editor
    |--------------------------------------------------------------------------
    |
    | Choose your preferred editor to use when clicking any edit button.
    |
    | Supported: "phpstorm", "vscode", "vscode-insiders",
    |            "sublime", "atom"
    |
    */

    'editor' => env('IGNITION_EDITOR', 'phpstorm'),
```

An open source project shouldn't deliberately encourage a closed source one ("phpstorm"). Default editor should be switched to either "vscode" or "atom" in this case.

In the long term it would be nice to have more options, like "eclipse" and "netbeans", etc.

**Comment by riasvdv** [comment]
If you want to have more editor options, feel free to add them in a PR!

**Comment by DanAlexson90** [comment]
> If you want to have more editor options, feel free to add them in a PR!

That's not what issue was about, issue was about `'phpstorm'` (current default option).
