### ISSUE TITLE
First frame is not shown in list until you have reached the second

### ISSUE THREAD

**Issue by willemvb** [facade/ignition#250]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/1336390/74868513-aba17700-5356-11ea-8d22-1d15b9014867.png">

First frame only shows up after you've clicked nr. 2. At the same time, the line number of the selected nr. 2 disappears.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/1336390/74869107-aabd1500-5357-11ea-80e6-f7b19dd3a3fe.png">

**Comment by AdrianMrn** [comment]
I fixed this in https://github.com/facade/ignition-js/issues/22

We can deploy it after merging it in https://github.com/facade/ignition/pull/248
