### ISSUE TITLE
Ignition crashes in Laravel 7

### ISSUE THREAD

**Issue by driesvints** [facade/ignition#251]
Was trying to debug a routing issue in Laravel 7 and Ignition showed up as following:

![Screenshot 2020-02-24 at 08 06 14](https://user-images.githubusercontent.com/594614/75133870-b2c0e000-56dc-11ea-90ef-c190453de234.png)

To reproduce:

- `laravel new test-laravel7 --dev`
- `valet link`
- Comment out default api route
- Change contents of `web.php` to:

```php
Route::view('/', 'welcome');
```

And you'll see the above screen when visiting `test-laravel7.test`.

**Comment by GrahamCampbell** [comment]
Is this related to https://github.com/facade/ignition/issues/252 perhaps?

**Comment by driesvints** [comment]
Seems to be fixed now 👍 

(Above steps to reproduce won't work anymore because the bug in Laravel itself was fixed)
