### ISSUE TITLE
More than one 2.x branch

### ISSUE THREAD

**Issue by GrahamCampbell** [facade/ignition#252]
There is a 2.x branch but also master is aliased to 2.x. Which is meant to be 2.x?

**Comment by freekmurze** [comment]
Branch `v2` will be `v2.0.0` and is compatible with Laravel 7.

**Comment by GrahamCampbell** [comment]
Ok, then the branch alias in the master branch is wrong.

**Comment by GrahamCampbell** [comment]
I've sent a PR to correct this. :)
