### ISSUE TITLE
Class 'Facade\Ignition\IgnitionServiceProvider' not found

### ISSUE THREAD

**Issue by giantthinker** [facade/ignition#259]
I have this error after upgrading laravel from 6 to 7.

`In ProviderRepository.php line 208:
                                                             
  Class 'Facade\Ignition\IgnitionServiceProvider' not found`

**Comment by freekmurze** [comment]
Our tests prove that v2 is working properly. Probably you've already solved this. 

For people stumbling on this, I think you can solve it by clearing caches and removing the temporary stuff in the `bootstrap` directory.
