### ISSUE TITLE
[Error] SyntaxError: Invalid regular expression: unmatched parentheses

### ISSUE THREAD

**Issue by mikebronner** [facade/ignition#261]
I've been getting the following error since implementing LiveWire. I wonder if there is an underlying conflict somewhere, or that the LiveWire code is interrupting Ignition's process?

Any suggestions how to allow them to throw errors and get along would be great! Thanks! :)

```
[Error] SyntaxError: Invalid regular expression: unmatched parentheses
	(anonymous function) (edit:204)
[Error] TypeError: window.ignite is not a function. (In 'window.ignite(window.data)', 'window.ignite' is undefined)
	Global Code (edit:213)
[Error] ReferenceError: Can't find variable: Ignition
	Global Code (edit:216)
```

**Comment by freekmurze** [comment]
We didn't get any other reports on this and didn't encounter this issue ourselves.

Closing this for now. Feel free to open up a new issue should the error pop up again in the latests versions of Ignition / Livewire.
