### ISSUE TITLE
FYI exception view impossible to read in Nova

### ISSUE THREAD

**Issue by tanthammar** [facade/ignition#266]
Suppose this is not on your plate but thought you might want to know:
Laravel 7.3.0, Nova 3.1.0 with default theme.

https://github.com/laravel/nova-issues/issues/2467

<img width="316" alt="Skärmklipp 2020-03-31 15 05 04" src="https://user-images.githubusercontent.com/21239634/78030214-040a6200-7362-11ea-98e3-669af0010a49.png">

**Comment by freekmurze** [comment]
I'm thinking this should be solved at the Nova side.
