### ISSUE TITLE
Prefix for file paths (for Homestead users)

### ISSUE THREAD

**Issue by klaasgeldof** [facade/ignition#27]
If you use Homestead, the real paths of your code files look something like this:

`/home/vagrant/code/myproject/app/Http/Controllers/MyController.php`

But on my computer, that isn't the real path to the file. Instead, this is the correct path:

`/Users/klaas/Documents/Code/myproject/app/Http/Controllers/MyController.php`

So if I click the pencil icon on the Ignition page, the file is not found.

I suggest you can add a prefix in the Ignition config file, like this:

```php
[
    'path_prefix' => '/Users/klaas/Documents/Code/myproject',
]
```

If defined, it gets prefixed to the paths, which can be done like this for example:

```php
if ($prefix = config('ignition.path_prefix')) {
    $path = $prefix.substr($path, strlen(base_path()));
}
```

**Comment by simon511000** [comment]
I have exactly the same problem as @klaasgeldof, his fix is perfect!

**Comment by freekmurze** [comment]
If you have the time, feel free to send a PR for this.

**Comment by Elgoist** [comment]
Working on a PR. Docker Development is broken as well.

**Comment by freekmurze** [comment]
`remote-sites-path` and `local-sites-path` config keys have been value to the config file that'll help you solve this. Thanks for the PR @mikebronner 👍

**Comment by mikebronner** [comment]
🤙

**Comment by klaasgeldof** [comment]
Great, thanks! 😃

Purist comment: config keys should be snake case, so:

`remote-sites-path` => `remote_sites_path`
`local-sites-path` => `local_sites_path`

Now there are mixed cases in the config file.

**Comment by freekmurze** [comment]
@mpociot is on it!
