### ISSUE TITLE
Limited Cross-Site Scripting in /_ignition/scripts and /_ignition/styles Endpoint 

### ISSUE THREAD

**Issue by fbogner** [facade/ignition#273]
The default endpoints /_ignition/scripts/ and /_ignition/styles/ are vulnerable to cross-site scripting in Internet Explorer. Because IE does not use URL encoding in its HTTP requests, the described endpoints can be abused to inject HTML.

The issue is caused by the fact that our XSS payload is not a valid array index ($request->script):
`Ignition::scripts()[$request->script]` 
(see: https://github.com/noonnightcoder/aec/blob/master/vendor/facade/ignition/src/Http/Controllers/ScriptController.php)

**Example:** 
`https://your.install.com/_ignition/scripts/--><h1>XSS - Cross Site Scripting<div style="display:none">`
<a href="https://ibb.co/GdRQwFc"><img src="https://i.ibb.co/QJMvBXr/Untitled.jpg" alt="Untitled" border="0"></a>

One possible solution could be to check, it the array index is valid, or to ensure that the "array index" is properly URL encoded.

**Comment by fbogner** [comment]
Update: The issues is NOT limited to Internet Explorer.

It also works on Firefox and Chrome. I guess I missed something during my initial testing.

**Comment by freekmurze** [comment]
Could you submit a PR that fixes this. 

I'm thinking this is only a problem if you have APP_DEBUG set to true, which you should never do in any environment that processes sensitive information.
