### ISSUE TITLE
does ignition also work with lumen?

### ISSUE THREAD

**Issue by 8ctopus** [facade/ignition#276]
I tried to follow the installation instructions, but couldn't get it to work with lumen 7.1.2.

`composer require facade/ignition`

**Comment by simonschaufi** [comment]
Lumen is an API Framework, where you typically get JSON back. Why would you need a frontend error handler in that case?

**Comment by freekmurze** [comment]
In theory it should work on Lumen, open up an issue/PR if it doesn't work for you.

**Comment by luciano-work** [comment]
Hi 👋
Are there some documentation that explain how to config Ignition with Laravel Lumen?
After install using composer and create some exception, my project still using Symfony Exception

I found how to config flare, but not Ignition 😢
https://flareapp.io/blog/3-using-flare-with-lumen

**Comment by luciano-work** [comment]
> In theory it should work on Lumen, open up an issue/PR if it doesn't work for you.

Please, tell me how to config in Lumen 8 😬
