### ISSUE TITLE
Ability to control Context formatting

### ISSUE THREAD

**Issue by jackmcdade** [facade/ignition#28]
Statamic has its own template language and I'd love to be able to show our view in the Context area, but it's just one giant blob of text. Is there any way to throw a `<pre>` around that, or is a Tab the only way to go?

**Comment by riasvdv** [comment]
@jackmcdade Is this still relevant? What kind of view would you like to show? Seems like the Antlers view gets shown correctly when an exception occurs:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/3626559/87341939-ada8e400-c54a-11ea-9c65-d9941e1d1169.png">

**Comment by freekmurze** [comment]
Closing as this issue seems to have been solved somewhere along the way.

**Comment by jackmcdade** [comment]
Yup seems fine these days, thanks!
