### ISSUE TITLE
Visibility / width 

### ISSUE THREAD

**Issue by mgralikowski** [facade/ignition#283]
![Screenshot_9](https://user-images.githubusercontent.com/17027876/86488158-62c7e900-bd60-11ea-9672-543090662e81.png)

I tried ignition 1.x with Laravel 6 but finally I returned to whoops. Look at the image above. I have a 2560 screen monitor and 50% of the screen is unused - white empty space. It is such a waste and as You can see in whoops I see full path and line number. This page is for devs, I guess most of us use the wide screen to programming. Why not use a responsive template or allow to set max-width in the config file?

**Comment by AdrianMrn** [comment]
Hi @mgralikowski! We appreciate your feedback, and understand why this is annoying to you.

The path in your screenshot is supposed to wrap (see my screenshot below), this only seems to be going wrong on Windows. I'll set up a Laravel environment on my Windows PC and try to reproduce and fix that issue.

![image (44)](https://user-images.githubusercontent.com/12762044/86577706-f117b700-bf7a-11ea-87e0-85a8e08be3ae.png)

-----

For the next major version of ignition, we'll look into your comments about the width of the page. Your comment about the max-width config option definitely seems like something that could be considered! 🙂

**Comment by mgralikowski** [comment]
Yes, I use win 10 and Laragon locally. But how it is possible that CSS/HTML is dependent on OS?

**Comment by AdrianMrn** [comment]
@mgralikowski We're thinking this is an issue with how the report is created in ignition, specifically the way in which the path is evaluated. This may have something to do with Windows vs Unix-style delimiters (`\` vs `/`).

**Comment by mgralikowski** [comment]
Ah, I see.

**Comment by freekmurze** [comment]
@mgralikowski I've applied a fix to flare-client-php (https://github.com/facade/flare-client-php/commit/162797c9da58b1c709623bad49fd71c7c1f557c6) that should results in paths being displayed relative to you app directory.

If full paths remains after pulling in the latest version of flare-client-php, please open up a new issue.

I'd accept a PR that adds a config setting to control that `max-width` behaviour.
