### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tarampampam** [facade/ignition#284]
As you know, PHP processes can working for a long time. It is possible with, for example, [swoole](https://www.swoole.co.uk/) or [roadrunner](https://github.com/spiral/roadrunner) projects.

With long living processes we should take care about memory usage, and we have a report about memory leak in your package: https://github.com/spiral/roadrunner-laravel/issues/8

Can you try to fix this?

**Comment by freekmurze** [comment]
Could you give us a hint where this memory leak would be?

Does it occur if debug mode is set to false?

**Comment by tarampampam** [comment]
As you can see in https://github.com/spiral/roadrunner-laravel/issues/8#issuecomment-656202101 - default L7 installation without any configuration _(debug is disabled by default)_

**Comment by freekmurze** [comment]
As ignition is a dev dependancy, this shouldn't happen on project in production.

Because we don't get any other reports on this, and it this memory leak does not occur under normal conditions, we're not going to invest our time in this. 

We would however accept a PR that fixes this.

**Comment by driesvints** [comment]
FYI: Ignition isn't entirely a dev package when used in production in combination with Flare.
