### ISSUE TITLE
404 on facade\ignition-self-diagnosis repo

### ISSUE THREAD

**Issue by jackmcdade** [facade/ignition#29]
The <https://flareapp.io/docs/ignition-for-laravel/first-party-extensions> docs reference the `facade\ignition-self-diagnosis` but it's a 404. Is it still private, by chance?

**Comment by freekmurze** [comment]
Yeah, that one is still private, because @mpociot wanted to improve that package a bit still.

@mpociot Do you think we could already make it public?

**Comment by pxgamer** [comment]
Looks like this is now public? 🎉
https://github.com/facade/ignition-self-diagnosis

**Comment by mpociot** [comment]
Yep, it's now published. Sorry for the delay :)
