### ISSUE TITLE
Javascript error when opening code editor

### ISSUE THREAD

**Issue by mankowitz** [facade/ignition#293]
Browser: Chrome; Version 83.0.4103.116 (Official Build) (64-bit)
OS: Windows 10 Home; Version 1909
Laravel: version 7.17.2
Ignition: 2.0.7

When I have an exception in laravel code, the ignition code editor appears, but there are javascript errors which appear in the console:

`Uncaught ReferenceError: $options is not defined
    at patients?_token=HDukXfPOldmpVkZAwoNPW6rYIHj5YA8QTbMpCRO8&start-date=2020-07-11&end-date=2020-07-14&orderBy=LOS&sortOrder=asc&chart_status=incomplete&provider_id=:174
    at <anonymous>:1:1
    at m (javascript?v=1591726955:2)
    at Re (javascript?v=1591726955:2)
    at w.fn.init.append (javascript?v=1591726955:2)
    at w.fn.init.<anonymous> (javascript?v=1591726955:2)
    at z (javascript?v=1591726955:2)
    at w.fn.init.html (javascript?v=1591726955:2)
    at itemRenderer (javascript?v=1591726955:1488)
    at String.<anonymous> (javascript?v=1591726955:1419)
(anonymous) @ patients?_token=HDukXfPOldmpVkZAwoNPW6rYIHj5YA8QTbMpCRO8&start-date=2020-07-11&end-date=2020-07-14&orderBy=LOS&sortOrder=asc&chart_status=incomplete&provider_id=:174
(anonymous) @ VM2191:1
m @ javascript?v=1591726955:2
Re @ javascript?v=1591726955:2
append @ javascript?v=1591726955:2
(anonymous) @ javascript?v=1591726955:2
z @ javascript?v=1591726955:2
html @ javascript?v=1591726955:2
itemRenderer @ javascript?v=1591726955:1488
(anonymous) @ javascript?v=1591726955:1419
each @ javascript?v=1591726955:2
(anonymous) @ javascript?v=1591726955:1416
set @ javascript?v=1591726955:159
(anonymous) @ javascript?v=1591726955:291
set @ javascript?v=1591726955:159
(anonymous) @ javascript?v=1591726955:992
each @ javascript?v=1591726955:2
dataChangeHandler @ javascript?v=1591726955:986
showDataSet @ javascript?v=1591726955:974
addDataSet @ javascript?v=1591726955:933
(anonymous) @ patients?_token=HDukXfPOldmpVkZAwoNPW6rYIHj5YA8QTbMpCRO8&start-date=2020-07-11&end-date=2020-07-14&orderBy=LOS&sortOrder=asc&chart_status=incomplete&provider_id=:297
`

**Comment by redalpha01** [comment]
Do you perhaps have the debugbar activated? It seems to be when both are on at the same time.
