### ISSUE TITLE
Collapase vendor frames not working

### ISSUE THREAD

**Issue by dougfelton** [facade/ignition#295]
I'm seeing the same issue that was mentioned [here](https://github.com/facade/ignition/issues/241)

I'm not seeing any console errors.  I've cleared all caches, ran dumpautoload, removed and reinstalled ignition... to no effect.  Vendor frames always appear as expanded and clicking on "Collapse vendor frames" has not effect, nor produces any error in the console.  Here are my details:

Os: Windows 10

Browsers tested: 

- 	Firefox 78.0.2 (Official build) (64-bit)
- 	Google Chrome 84.0.4147.89 (64-bit)
- 	Microsoft Edge Version 84.0.522.40 (Official build) (64-bit)

laravel/framework: 7.20.0
facade/ignition: 2.3.3

Any thoughts?

**Comment by AdrianMrn** [comment]
Hi @dougfelton, I can't seem to reproduce this easily. If you are willing to create an example repository where this bug is present, I'll have a go at fixing it.
