### ISSUE TITLE
Laravel Ignition Blank Screen

### ISSUE THREAD

**Issue by imichaelv** [facade/ignition#296]
Hello Developers/Contributors, 

Since the error still exists this might come over as a repost.

Original issue: https://github.com/facade/ignition/issues/221 (closed 9 days ago, due to not being able to reproduce)

When stumping upon a error like this one: 
```php
<?php
function foo(){
   return user()->BadMethodCallDueToTypooooo(); 
}
```

The page will stay blank and will not render the JavaScript view of Ignition. 

As mentioned before by @soufianesabiri its lies into the `windows.tab = <?=$tabs?>;` code. 
He fixed it with the underlaying example.

> So I commented this line and it worked...
>
>```
>//window.tabs = <?=$tabs?>;
>```
>in the file:
> \vendor\facade\ignition\resources\views\errorPage.php

In my case I tried using `dd($tabs)` to see whats in it and it responded with `[]`

This causes an error on Chrome 83.0.4103.116 on Windows 10.  (michtest = the page where I cause a error)
With a Laravel application
```
michtest:87 TypeError: Cannot read property 'forEach' of undefined
    at a.tabs (michtest:92)
    at gn.get (michtest:87)
    at gn.evaluate (michtest:87)
    at a.tabs (michtest:87)
    at a.mounted (michtest:92)
    at Gt (michtest:87)
    at rn (michtest:87)
    at Object.insert (michtest:87)
    at C (michtest:87)
    at Tn.__patch__ (michtest:87)
```

Looking more into the code and dependancies I have I can't see where the Ignition->tab(Tab $tab) function is being called from. Suggesting this might be not being initialized further than `[]`. 

Is it posible to remove this code or create a fallback so this bug wont happen?
https://github.com/facade/ignition/blob/a1ebe576d7d15b8079c414986602eeb94bdcd625/resources/views/errorPage.php#L42

Would be nice to see a update for this, since I'm working on a upgrade for laravel from 5.4 to ^7.0

**Comment by imichaelv** [comment]
Did some extra testing with the window.tab row.

```
window.tabs = <?=$tabs?>; 
```
If replaced like one of these wont result to the error, so It looks like its mainly on the $tabs variable:
```
window.tabs = 'randomString'; 
window.tabs = [];
window.tabs = null;
```

**Comment by freekmurze** [comment]
We'll take a look soon. Feel free to already submit a PR that fixes this for you.

**Comment by jomisa** [comment]
Blank screen when error thrown in ingnition and takes forever (localhost - windows linux subsystem - ubuntu 20.04 - nginx 1.18.0 - Laravel 7.20 - php 7.4). 

But
Can get some response (html in response body) using postman (also takes forever).
storage log files works fine
project folder with chmod -R 777
Works fine deployed in AWS Elastic Beanstalk (EC2 t2.micro)

above solutions didnt help 

1. config/ignition.php
'ignored_solution_providers' => [
        \Facade\Ignition\SolutionProviders\IncorrectValetDbCredentialsSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\MissingAppKeySolutionProvider::class,
        \Facade\Ignition\SolutionProviders\DefaultDbNameSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\BadMethodCallSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\TableNotFoundSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\MissingImportSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\MissingPackageSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\InvalidRouteActionSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\ViewNotFoundSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\UndefinedVariableSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\MergeConflictSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\RunningLaravelDuskInProductionProvider::class,
        \Facade\Ignition\SolutionProviders\MissingColumnSolutionProvider::class,
        \Facade\Ignition\SolutionProviders\UnknownValidationSolutionProvider::class,
    ],

2. config/flare.php
'collect_git_information' => false,

3. \vendor\facade\ignition\resources\views\errorPage.php
//window.tabs = <?=$tabs?>;

My nginx configuration:

server {
    listen 80;
    server_name mysubdomain.localhost;
    root "route/To/My/Project/Public/Directory";

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

**Comment by rubenvanassche** [comment]
Hi guys, I cannot reproduce this issue, but let's not stop here and try to find a solution!

First off all, what I did was adding the following code to my routes file:

```php
Route::get('/', function () {
    return user()->BadMethodCallDueToTypooooo();
});
```

This did not result in an error, so could you please provide me an exact example how this error comes through?

Also, at the moment I'm using Laravel 7.21.0 and Ignition 2.3.3, could you please check what the versions are on your setup?

**Comment by jomisa** [comment]
My setup 
Laravel 7.21 and ignition 2.3.3

Http response takes forever, Html body doesnt load (blank page), html header loading.

![image](https://user-images.githubusercontent.com/10745773/88394221-ab355e00-cd84-11ea-893f-41e932c9eb6f.png)

**Comment by imichaelv** [comment]
think I found out the problem.

```javascript
window.data = <?=
        $jsonEncode([
            'report' => $report,
            'config' => $config,
            'solutions' => $solutions,
            'telescopeUrl' => $telescopeUrl,
            'shareEndpoint' => $shareEndpoint,
            'defaultTab' => $defaultTab,
            'defaultTabProps' => $defaultTabProps,
        ])
    ?>
    window.tabs = <?=$tabs?>;
```

there is a missing ";" at the end of the first php part. 
https://github.com/facade/ignition/blob/a1ebe576d7d15b8079c414986602eeb94bdcd625/resources/views/errorPage.php#L40
so it looks like its a window.data = [...] window.tabs = [] for the browser. 


if you add the ; before windows.tabs it works again. (or remove window.tabs)
```javascript
window.data = <?=
        $jsonEncode([
            'report' => $report,
            'config' => $config,
            'solutions' => $solutions,
            'telescopeUrl' => $telescopeUrl,
            'shareEndpoint' => $shareEndpoint,
            'defaultTab' => $defaultTab,
            'defaultTabProps' => $defaultTabProps,
        ])
    ?>;
    window.tabs = <?=$tabs?>;
```

**Comment by rubenvanassche** [comment]
@imichaelv first of all, thank you for the research!

Still can't reproduce the issue(I guess my browser ignores the issue), but that code does not look correct, I've released an updated version of Ignition(2.3.4) with the extra `;`, this should fix the problem. I will close this issue, but should it still pop-up then please reopen it so we can keep searching for a fix.

**Comment by jomisa** [comment]
Hi, this fix makes sense, but didnt  solve the issue, blank error html body page

**Comment by jomisa** [comment]
Windows Linux Subsystem issue

php-fpm configuration setup recomendation
https://stackoverflow.com/questions/46286420/php7-0-fpm-extremly-slow-on-ubuntu-windows-subsystem-linux

**Comment by rubenvanassche** [comment]
Hi @jomisa,

Do you have any extensions added to Ignition because I can't reproduce the issue?

**Comment by jomisa** [comment]
Hi @rubenvanassche I have no extensión in ignition, actually it also happens in fresh New installs, Just a Windows subsystem Linux performance issue. Ended up using whoops (slow but al least it renders debug page) instead of ignition in my development setup.

**Comment by rubenvanassche** [comment]
@jomisa Thanks for the information, I hope this issue is getting fixed quickly!
