### ISSUE TITLE
Stack trace frames are not always formatted properly

### ISSUE THREAD

**Issue by AlexVanderbist** [facade/ignition#298]
Sometimes a frames from separate files in the stack trace are formatted as if they're in the same file. Consider the following example:

![image](https://user-images.githubusercontent.com/6287961/88558395-beb62280-d02b-11ea-8b75-57c7776d810a.png)

`UpdateEventPricingCardController.php` and `ProductPricingCardData.php` should be purple/bold as they're not part of `
ProductPriceData.php`.

**Comment by AdrianMrn** [comment]
I believe I've fixed this in a separate repo in this commit: https://github.com/facade/ignition-ui/commit/99beb13534c24e2882755683dd604aa2b4970264

**Comment by freekmurze** [comment]
Closing this as we're not going to invest too much time in facade/ignition anymore, but are concentrating on getting spatie/ignition.
