### ISSUE TITLE
Docs repo?

### ISSUE THREAD

**Issue by jackmcdade** [facade/ignition#30]
Are the docs in a repo anywhere? There are a number of typos and broken links I would be more than happy to fix and send PRs for. If not, how would you like them reported?

**Comment by freekmurze** [comment]
Hi Jack, thanks for wanting to help out improving our docs.

Currently the markdown files that are used to render our docs are not in a public repo. They live in a private repo with the rest of our app code. in the next few weeks, we'll take a look at how we could put those files in a public repo so you can PR improvements.

For now, feel free to post the typos and broken links you find in this issue (or mail them to freek@spatie.be) and I'll fix them manually.

**Comment by freekmurze** [comment]
We've published our docs in [this repo](https://github.com/facade/flare-docs). Feel free to send a PR to fix typos and broken links.
