### ISSUE TITLE
Facade\Ignition\LogRecorder\LogRecorder::$logMessages memory limit

### ISSUE THREAD

**Issue by flysion** [facade/ignition#301]
//in vendor/facade/ignition/src/LogRecorder/LogRecorder.php

    public function record(MessageLogged $event): void
    {
        if ($this->shouldIgnore($event)) {
            return;
        }

        $this->logMessages[] = LogMessage::fromMessageLoggedEvent($event);
    }

Version:Laravel-7.22.4
Error:PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4194312 bytes)

**Comment by rubenvanassche** [comment]
This should be fixed with version 2.5.12, thanks @TheLevti for the fix!
