### ISSUE TITLE
Laravel 8.x error

### ISSUE THREAD

**Issue by bpedroza** [facade/ignition#306]
`Too few arguments to function Illuminate\View\Engines\PhpEngine::__construct(), 0 passed in \vendor\facade\ignition\src\IgnitionServiceProvider.php on line 128 and exactly 1 expected`

`Illuminate\View\Engines\PhpEngine` constructor now expects `Illuminate\Filesystem\Filesystem` to be passed to the constructor.

**Comment by freekmurze** [comment]
Could you provide us with steps on how to reproduce this error?

**Comment by bpedroza** [comment]
Sure. I tried to fork and get a failing test going, but it looks like `psalm/plugin-laravel` isn't ready to support laravel 8.x in their composer.json yet.

Manual Steps to reproduce:
1. Setup laravel 8.x project (this will change after release I assume)
    a. git clone --single-branch --branch develop https://github.com/laravel/laravel.git ignition-test
    b. cd ignition-test
    c. composer install
    d. cp .env.example .env
    e. php artisan key:generate
2. Create a php view `test.php` in `resources/views`
3. Add a route to the web.php file `Route::get('/test', function() {return view('test');});`
4. php artisan serve
5. visit http://localhost:8000/test and see the error

**Comment by freekmurze** [comment]
@AlexVanderbist could you take a look at this one?

**Comment by bpedroza** [comment]
@freekmurze @AlexVanderbist is it OK for me to submit a PR?

I checked `psalm/plugin-laravel` to see if I could make an update there to support laravel 8, but there is a circular reference happening, so the tests there all fail because of the issue here.

The fix is pretty simple and shouldn't be breaking since PHP just ignores the extra argument.
All tests pass for 7.x, but I won't be able to update the workflow to also test laravel 8 until the issues are resolved in both repos.

**Comment by freekmurze** [comment]
Sure, send in a PR! 👍

**Comment by bpedroza** [comment]
Great. Thank you.
