### ISSUE TITLE
Ignition page not shown on AJAX request

### ISSUE THREAD

**Issue by Nartub600** [facade/ignition#31]
I installed Ignition in a 5.8.34 Laravel and it's working when an error happens during navigation, but issuing an AJAX request and checking the devtools displays the original Symfony error page with this message:

![image](https://user-images.githubusercontent.com/1523762/64067281-a3b11780-cbfc-11e9-9c21-f2d23d17eb00.png)

**Comment by mpociot** [comment]
This was fixed in version 1.0.1 of flare-client-php, which caused this.
