### ISSUE TITLE
Lumen install documentation

### ISSUE THREAD

**Issue by luciano-work** [facade/ignition#315]
Hi 👋
Are there some documentation that explain how to config Ignition with Laravel Lumen?
After install using composer and create some exception, my project still using Symfony Exception

I found how to config flare, but not Ignition 😢
https://flareapp.io/blog/3-using-flare-with-lumen

**Comment by AlexVanderbist** [comment]
Hi @luciano-work 

I'm not sure if Ignition works on Lumen. It's the default error page for Laravel but it doesn't seem like Lumen comes with an error page out of the box. It's certainly not something we're looking at right now. If you can get it working I'd be happy to merge any changes to documentation that report your findings.

Maybe someone else here has experience with getting Ignition to work on Lumen?

Good luck
