### ISSUE TITLE
Blank screen with console log error

### ISSUE THREAD

**Issue by Piket564** [facade/ignition#318]
Hi,
I'm having some errors in console, I attach below, I also attach my composer.json conf

![image](https://user-images.githubusercontent.com/19176918/94945495-0b5e2400-04db-11eb-9011-b3ae76e9695c.png)

Here the composer:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "renatomarinho/laravel-page-speed": "^1.9",
        "spatie/laravel-blade-javascript": "^2.5",
        "spatie/laravel-mix-preload": "^1.2"
    },
    "require-dev": {
        "facade/ignition": "2.3.8",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```

My server has PHP  7.3, if this is not enough, I can upgrade to 7.4.
I can't understand what it can be.

Don't hesitate to ask for more information
I hope that was helpful.

**Comment by AdrianMrn** [comment]
Hi @Piket564!

What OS are you on?

Can you take a new screenshot with the full width of your console, so the errors include the file & line number where they occurred. Also, can you click through to that file, and take a screenshot of the resulting code?

**Comment by Piket564** [comment]
Hi @AdrianMrn,
I think i'm on CloudLinux.

![image](https://user-images.githubusercontent.com/19176918/94988243-1319d900-056c-11eb-9129-ebf2f5e7e8e5.png)

![image](https://user-images.githubusercontent.com/19176918/94988284-63913680-056c-11eb-82d5-545281e766f9.png)

**Comment by Piket564** [comment]
Hi @AdrianMrn,

after creating another blank project with Laravel 8, i found out that maybe the
`renatomarinho/laravel-page-speed`
is causing the issue

**Comment by AdrianMrn** [comment]
All right, from the screenshots I don't have any idea what could be causing this either.

If you still need help with this and you think it's related to the ignition project, could you create a repo with a small reproducible example?

**Comment by Piket564** [comment]
Hi @AdrianMrn,
thanks for the effort, I found the problem, the `laravel-page-speed` library was preventing the Ignition from loading correctly.
By updating version number and using composer update I solved all the problems.
I will close the report.
Thanks for the help.

**Comment by bytebrain** [comment]
For anyone who stumbles on this issue, I disabled the `laravel-page-speed` package on exceptions, by changing the `Handler.php`. 

```php
    protected function whoopsHandler()
    {
        // Disable the page speed package.
        config(['laravel-page-speed.enable' => false]);

        try {
            return app(\Whoops\Handler\HandlerInterface::class);
        } catch (\Illuminate\Contracts\Container\BindingResolutionException $e) {
            return parent::whoopsHandler();
        }
    }
```
