### ISSUE TITLE
Option to disable share tab

### ISSUE THREAD

**Issue by Vusys** [facade/ignition#32]
I don't want there to be even the possibility to send snippets of code and stack traces from internal and closed source applications to Flare. There needs to be an option to disable and remove the share button.

As a work around, there's an undocumented config (`flare.base_url`) to change where reports are sent to, and setting that to localhost seems to disable sharing by breaking it but obviously doesn't remove the button.

I'd like to see an option to disable sharing entirely, and ideally the report viewer part of Flare should be open sourced so we can self host reports.

**Comment by freekmurze** [comment]
We'll probably going to add this one in the coming weeks! 👍 If you want it even faster, feel free to submit a PR with tests that adds this to the package.

**Comment by AlexVanderbist** [comment]
Merged in https://github.com/facade/ignition/pull/52!
