### ISSUE TITLE
[Question] Why is the Highlight PHP package needed?

### ISSUE THREAD

**Issue by selcukcukur** [facade/ignition#321]
I could not understand exactly why it was needed.

**Comment by freekmurze** [comment]
I think we used to use that one to hightlight code. We'll investigate if this dependency is still needed. If not, we'll remove it.

**Comment by selcukcukur** [comment]
@freekmurze Thanks.

**Comment by selcukcukur** [comment]
#324 As a result of my investigations, I saw that there is no need.

**Comment by AlexVanderbist** [comment]
Thanks! Will take a look now :)
