### ISSUE TITLE
PHPStorm editor links only work on Mac

### ISSUE THREAD

**Issue by RobertBoes** [facade/ignition#33]
The `phpstorm://` scheme currently only works on Mac, it requires a third party plugin to work on Windows/Linux, like [aik099/PhpStormProtocol](https://github.com/aik099/PhpStormProtocol). As mentioned in #27 this also doesn't work when Homestead is used.

IntelliJ also exposes an REST API at `http://localhost:63342/`, see https://www.develar.org/idea-rest-api/#api-Platform-about but then Ignition has to make a get request to `http://localhost:63342/api/file?file=routes/web.php&line=17` for example. 
<details><summary>Remove the warning popups</summary>
<p>

Settings -> Build, Execution, Deployment -> Debugger -> Check "Allow unsigned requests" under Built-in server removes the warning popups

![image](https://user-images.githubusercontent.com/2871897/64070067-22d43900-cc59-11e9-8b87-53827bcdedf5.png)

</p>
</details>

Another option is to use the `jetbrains://` scheme, that's included in Jetbrains Toolbox. The scheme works on all platforms, however I couldn't get that scheme to open any files, only errors.

So since PHPStorm currently doesn't support opening files that well, would it be worth investing time in a PR which makes for a better cross-platform compatibility? Or maybe just make it possible to disable the "open file" feature and adding notes to the config file or docs?

**Comment by rokde** [comment]
**Additional Info**
It would be very nice if we could configure via callback or config option. We run our local development code within a docker container - so the linked path is always wrong. So if you make the link url configurable we could change the base path with the protocol used to suit more our needs.

**Comment by emptimd** [comment]
Installing aik099/PhpStormProtocol on Ubuntu dose not help. The http://localhost:63342/ port works good, maybe use it if phpstorm is the chosen editor.

**Comment by Gummibeer** [comment]
I would say that Ignition does it the common way. It's the same like in Whoops all time before.

https://github.com/filp/whoops/blob/3f37a6481add76551d6f27f655a3c6317eda8559/src/Whoops/Handler/PrettyPageHandler.php#L102-L112
https://github.com/facade/ignition/blob/b9081637e856ae55a7c5ff981750696c0d983f3d/resources/js/components/Shared/editorUrl.js#L3-L13

**Comment by emptimd** [comment]
Thats strange because i remember it working with whoops in laravel 5.3

Heres error that i get:

Cannot find file '/home/user/./%2Fhome%2Fuser%2Fsites%2Fwebsockets%2Fresources%2Fviews%2Fwelcome.blade.php'

And yes i should install aik099/PhpStormProtocol to at least get this error on ubuntu. Anybody has this working on ubuntu?

**Comment by raveren** [comment]
+1 for the REST API at `http://localhost:63342/` or simply configuring custom file link formats.

**Comment by zschuessler** [comment]
+1 for using the PHPStorm API instead, but allowing custom protocols to be specified is probably the real solution here.

**Comment by zschuessler** [comment]
Anyone looking for a quick hack for this, I posted one here:

https://github.com/facade/ignition/pull/112#issuecomment-589757862

**Comment by freekmurze** [comment]
@zschuessler Is working on a PR that will fix this.
