### ISSUE TITLE
Livewire URL

### ISSUE THREAD

**Issue by bomshteyn** [facade/ignition#330]
When using with Livewire the URL being reported by the flareapp is not very useful.

URL: `https://example.com/livewire/message/app.quote.details`

While this tells me the location of the Livewire component it's not a URL that should be clicked as it will return 405. And if the component is used on multiple pages that is even less useful.

I believe the `referer` header on the request tab would be the correct URL.

**Comment by rubenvanassche** [comment]
Hi @bomshteyn,

Support for this was added in ignition 3.5.1, thanks for reporting!
