### ISSUE TITLE
'SolutionProviderRepository' not found

### ISSUE THREAD

**Issue by Muhammad-Sarfaraz** [facade/ignition#331]
After a fresh laravel project installation ,These errors occurred from nowhere.

In SolutionProviderRepository.php line 12:

  Interface 'Facade\IgnitionContracts\SolutionProviderRepository' not found

**Comment by rubenvanassche** [comment]
Hi @Muhammad-Sarfaraz,

Could you try this again with a more recent version of ignition? Just tried this with a fresh new Laravel project and everything is working as expected
