### ISSUE TITLE
PHP 7.2 and dependencies

### ISSUE THREAD

**Issue by dragermrb** [facade/ignition#333]
Ignition requires php ^7.2.5|^8.0 and depends on facade/ignition-contracts: ^1.0.2, but ignition-contracts requires php ^7.3|^8.0, so you cannot install facade/ignition with php7.2

**Comment by justijndepover** [comment]
I'm having the same problem. Trying to install facade v1 on php 7.1 is not possible

**Comment by driesvints** [comment]
Require `facade/ignition-contracts:1.0.1` specifically and you should be able to install Ignition v2 on PHP 7.2 and Ignition v1 on PHP 7.1

**Comment by dragermrb** [comment]
Thanks Dries
