### ISSUE TITLE
Solutions aren't displayed when an exception is triggered via a view

### ISSUE THREAD

**Issue by jasonvarga** [facade/ignition#35]
Congrats on the launch, it's looking great! 🎉 

I'm noticing that an error from within a view doesn't show me the solution, I'm assuming is because it's being rethrown as a `ViewException`.

This shows me the solution:

```
Route::get('/', function () {
    throw new ExceptionWithSolution;
});
```

This doesn't:

```
class Foo
{
    function error()
    {
        throw new ExceptionWithSolution;
    }
}


Route::get('/', function () {
    return view('myview', ['foo' => new Foo]);
});


{{ $foo->error() }}
```

**Comment by mpociot** [comment]
Thanks!
We now check if the exception contains a solution and then pass it to the view exception class

**Comment by jasonvarga** [comment]
Works perfectly. Thanks!
