### ISSUE TITLE
Circular references in Route parameters

### ISSUE THREAD

**Issue by Nyratas** [facade/ignition#352]
Hi there,

We found an issue with circular references when Ignition is rendering an Exception page. In our case there is a model containing a reference to itself in its relations that has been set as a route parameter. Whenever ignition is displaying an error page, it breaks and throws an nginx 502 bad gateway. This issue is resolved by removing the circular reference in the object stored as a route parameter. 

My guess is that the "Route parameters" preview under the "App" tab does not handle circular references, which could actually be quite common...

Here is a simplified screenshot of what we cannot display correctly :

![image](https://user-images.githubusercontent.com/5635557/107636611-2e5cc980-6c6d-11eb-9a3f-88875abd9034.png)

**Comment by Nyratas** [comment]
Update :

We were able to narrow it down to [this line](https://github.com/facade/ignition/blob/master/src/Context/LaravelRequestContext.php#L72) :

```php
return collect(optional($this->request->route())->parameters ?? [])->toArray();
```

This is actually a common issue we encountered a few times with `toArray()` which does not handle circular references at all.

**Comment by rubenvanassche** [comment]
Hi @Nyratas,

Could you provide me a code example of such circular dependency? Then we'll try to fix this.

**Comment by Nyratas** [comment]
Hi @rubenvanassche,

This is a simplified version of the case we actually encountered, which takes place in a middleware. I narrowed it down to the essentials. Here you go : 

```php
$category = Category::findOrFail(1);
$product = $category->products()->findOrFail(1);

$category->setRelation('product', $product);
$product->setRelation('category', $category);

request()->route()->setParameter('category', $category);
```

I hope this is sufficient ? Let me know if you need more info.

Thanks!

**Comment by NEGits** [comment]
We run into this almost every day, because we've got circular references in many route parameters. It makes ignition almost useless for us unfortunately. Is there a workaround for this bug?

**Comment by freekmurze** [comment]
Currently, we're not actively working on this, as this doesn't impact many people.

If you need this fixed fast, we'd appreciate a PR.
