### ISSUE TITLE
Incorrect error with variable issues in a view composer

### ISSUE THREAD

**Issue by FatBoyXPC** [facade/ignition#355]
When a view composer has an issue with a variable missing, or calling a method on a null variable, etc. the suggested fix is for the template rather than the view composer.

The screenshot shows this best: 
![image](https://user-images.githubusercontent.com/744962/107990260-0ab5be00-6fa2-11eb-910e-69bf2c4cdd5c.png)

**Comment by freekmurze** [comment]
We'll fix this in spatie/laravel-ignition.
