### ISSUE TITLE
ask first if $_SERVER has index arcv

### ISSUE THREAD

**Issue by caherrera** [facade/ignition#357]
I'm running some feature tests using phpunit and fails when trying to run some tests.

![image](https://user-images.githubusercontent.com/18551113/108513357-405bef00-72a1-11eb-99af-67aa7ee28925.png)

I'd suggest change replace this line
https://github.com/facade/ignition/blob/5e9ef386aaad9985cee2ac23281a27568d083b7e/src/IgnitionServiceProvider.php#L82

for this

![image](https://user-images.githubusercontent.com/18551113/108513465-67b2bc00-72a1-11eb-9187-bb3c7155a254.png)

**Comment by rubenvanassche** [comment]
Hi @caherrera,

Thanks for the suggestion, this is fixed in ignition v2.15.14!
