### ISSUE TITLE
2.8.0 emerging questions in laravel framework v8.34.0

### ISSUE THREAD

**Issue by Linij** [facade/ignition#374]
Argument 1 passed to Facade\FlareClient\Flare::censorRequestBodyFields() must be of the type array, null given, called in /home/htdocs/api/vendor/facade/ignition/src/IgnitionServiceProvider.php on line 134 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Facade\\FlareClient\\Flare::censorRequestBodyFields() must be of the type array, null given, called in /home/htdocs/api/vendor/facade/ignition/src/IgnitionServiceProvider.php on line 134 at /home/htdocs/api/vendor/facade/flare-client-php/src/Flare.php:235)
[stacktrace]
#0 /home/htdocs/api/vendor/facade/ignition/src/IgnitionServiceProvider.php(134): Facade\\FlareClient\\Flare->censorRequestBodyFields(NULL)
#1 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(672): Facade\\Ignition\\IgnitionServiceProvider->register()
#2 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Facade\\Ignition\\IgnitionServiceProvider))
#3 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load(Array)
#4 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#5 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#6 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#7 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#8 /home/htdocs/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#9 /home/htdocs/api/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#10 {main}
"}

**Comment by maegnes** [comment]
+1

Experiencing the same error

**Comment by tarreislam** [comment]
Hi,

I solved it and made a PR, check this out meanwhile

https://github.com/facade/ignition/issues/375

**Comment by rubenvanassche** [comment]
Thanks for bringing this to our attention, we've just released ignition 2.8.1 which should fix the issue
