### ISSUE TITLE
Argument 1 passed to Facade\FlareClient\Flare::censorRequestBodyFields() must be of the type array, null given, called in /var/www/vendor/facade/ignition/src/IgnitionServiceProvider.php on line 134

### ISSUE THREAD

**Issue by tarreislam** [facade/ignition#375]
Hi, the new update breaks everything because of array type hinting on null value in `register` part

`Argument 1 passed to Facade\FlareClient\Flare::censorRequestBodyFields() must be of the type array, null given, called in /var/www/vendor/facade/ignition/src/IgnitionServiceProvider.php on line 134`

Solved by manually adding  missing properties to `config\flare.php`  

` 'censor_request_body_fields' => ['password'],`

**Comment by tarreislam** [comment]
created pull

https://github.com/facade/ignition/pull/376

**Comment by rubenvanassche** [comment]
Thanks for bringing this to our attention, we've just released ignition 2.8.1 which should fix the issue.
