### ISSUE TITLE
App-Debug on Production error

### ISSUE THREAD

**Issue by bernhardh** [facade/ignition#380]
I am getting the error

> APP_DEBUG is set to true while APP_ENV is not local
>
> This could make your application vulnerable to remote execution. Read more about Ignition security.

The reason for this is, that I activate the `app.debug` setting in`NovaServiceProvider` (`config(["app.debug" => true]);`). Our Nova instance is only used by technical users, so we activated debug, to see helpfull error messages and not only useless "an error occured" messages.

We have set `IGNITION_ENABLE_RUNNABLE_SOLUTIONS` to false, so the above error message shouldn't be showed.

The error occurs since update to `v2.7.0`. Switching back to `v2.6.1` solves the problem.

**Comment by freekmurze** [comment]
Wouldn't it be easier to set the environment to `local` in this case?

**Comment by bernhardh** [comment]
Not sure if this has other side effects?

I used my current settings since a couple of months without any issues. Just the last update breaks it.

**Comment by freekmurze** [comment]
The update doesn't "break" your app, it just that extra message that bothers you right?

In that case, I'm going to leave things as they are. In think that the vast majority of users will not run their apps in production mode with debug mode on.
