### ISSUE TITLE
Debug Tab Error: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dhcmega** [facade/ignition#394]
Hi
All works except for DEBUG, it gives blank info because of this console error:

TypeError: Cannot read property 'length' of undefined

I tried upgrading, deleting caché, etc.
Any ideas on how can I fix it?

v2.10.1 with laravel v8.46.0

Thanks!

**Comment by freekmurze** [comment]
I couldn't reproduce this, so maybe it's already fixed?

**Comment by dhcmega** [comment]
Hi, not really:
```
1:43 TypeError: Cannot read properties of undefined (reading 'length')
    at a.<anonymous> (1:68)
    at a.t._render (1:43)
    at a.r (1:43)
    at mn.get (1:43)
    at new mn (1:43)
    at 1:43
    at a.Tn.$mount (1:43)
    at a.Tn.$mount (1:43)
    at init (1:43)
    at 1:43
Wt @ 1:43
```

This happens while using ddd(), under the Debug tab. The other tabs work ok.

I have even recreated the project in a new server. But it seems that this this is happening to me only.
Thank you anyway
