### ISSUE TITLE
facade/ignition does not work without filp/whoops

### ISSUE THREAD

**Issue by louisitvn** [facade/ignition#400]
facade/ignition version 2.11.0 is claimed to work without filp/whoops. However, after upgrading it and removing filp/whoops, my exception web UI turns back into the old red "Symfony Exception" page. It only works if I install filp/whoops back. Any suggestion?

**Comment by AlexVanderbist** [comment]
Hi @louisitvn, facade/ignition will keep using filp/whoops until Laravel 9.0. In 2.11.0 it was removed from the Ignition dependencies, but it's still required in laravel/framework ([here](https://github.com/laravel/framework/blob/8.x/composer.json#L83))

**Comment by louisitvn** [comment]
Perfect, thank you for the explanation. Very clear!
