### ISSUE TITLE
Call to protected method 'resetFlare'

### ISSUE THREAD

**Issue by mbardelmeijer** [facade/ignition#401]
With 2.11.1, there seems to be an issue with 'dispatch_now' jobs. We're getting the following errors directly after deploying the new version:

`Call to protected method Facade\Ignition\IgnitionServiceProvider::resetFlare() from context 'Illuminate\Events\Dispatcher'`

**Comment by rodrigopedra** [comment]
Got the same error after updating to 2.11.1 on Horizon. reverted back to 2.11.0

![image](https://user-images.githubusercontent.com/5470108/126330583-54a57ae6-833b-48a5-9f3a-aeb1cdb9b4e9.png)

**Comment by rodrigopedra** [comment]
ping @AlexVanderbist

**Comment by rodrigopedra** [comment]
PR #398 seems to be related to this issue

**Comment by dmason30** [comment]
Create a PR to make function public https://github.com/facade/ignition/pull/402

**Comment by Casmo** [comment]
Revert the changes in this commit fixed the issue for me:
https://github.com/facade/ignition/commit/2b94425e92948de7ff5f67c4b45cd114f31aeb4e#diff-b12e108bf46205d7aaa3d28bead8e2776878052ef7ae7dea1bc4d17f90f371b6L493-L495

**Comment by rodrigopedra** [comment]
Sent PR #403 to partial revert #398 

Didn't see PR #402 before sending it. Will keep both open so both options can be assessed

**Comment by dmason30** [comment]
@rodrigopedra Either looks good to me facada/spatie can decide 🚀

**Comment by rodrigopedra** [comment]
Sure thing @dmason30 you were very fast on this, thanks.

I added a comment to PR #403  saying yours (#402) is an alternative fix so they can decide faster instead of considering merging both.

**Comment by AlexVanderbist** [comment]
Sorry for the unfortunate oversight on our end. A fix has been released in v2.11.2. Thank you all for jumping on this so quickly :)
