### ISSUE TITLE
Context tab does not properly break sf-dump strings that contain long text.

### ISSUE THREAD

**Issue by randohinn** [facade/ignition#421]
![image](https://user-images.githubusercontent.com/14096473/135832289-63c3c04e-e3f2-4734-9c96-a5641f8fdeb3.png)
See attached image. The long strings (in this case a JSON string) are not linebroken properly.

**Comment by freekmurze** [comment]
Needs to be fixed in spatie/ignition as well.

**Comment by freekmurze** [comment]
We'll fix this in the upcoming spatie/ignition.
