### ISSUE TITLE
v1.* install issue with roave/security-advisories:dev-latest

### ISSUE THREAD

**Issue by jva91** [facade/ignition#426]
I'm using php7.2 with Laravel 6 LTS. Since two days it is impossible to run composer update with facade/ignition ^1.17 in composer.json when roave/security-advisories:dev-latest is present in composer.json.

Upgrading to ignition 2.* is not an option because of facade/ignition-contracts.

**Comment by jva91** [comment]
I couldn't find an issue with version 1.17 or above. Any idea why v1.* is flagged by roave?

**Comment by riasvdv** [comment]
This was added here: https://github.com/FriendsOfPHP/security-advisories/commit/d5c1af0f5e32ebfcdbec917622be15e6676b2a4d#diff-e0ad55e8dd489c2ed2e27e84207dbe1d0f7272ebe7dd55a778b05d351efe9406

[1.16.14](https://github.com/facade/ignition/releases/tag/1.16.14) fixes a security issue.
