### ISSUE TITLE
Introduce a way to disable certain solutions

### ISSUE THREAD

**Issue by freekmurze** [facade/ignition#44]
If somebody is not happy with a certain solution provider there should be a way to turn it off. 

Let's introduce a config key that can hold a list of ignores solutions.

**Comment by percymamedy** [comment]
Hello @freekmurze 

Did an attempt to ignore certain solutions, check PR https://github.com/facade/ignition/pull/49

Cheers !!

**Comment by freekmurze** [comment]
We’ll continue this conversation in #49
