### ISSUE TITLE
Uncaught ReferenceError: Ignition is not defined

### ISSUE THREAD

**Issue by ahmad96hijazi** [facade/ignition#441]
![image](https://user-images.githubusercontent.com/40335765/146500983-591105c3-3877-44d6-b0b8-21f7a48115c9.png)

Laravel showing plain 500 error (no Whoops or Ignition)

**Comment by rubenvanassche** [comment]
Hi @ahmad96hijazi,

Could you show me the source of the page?

**Comment by ahmad96hijazi** [comment]
it give a ^ symbol

**Comment by ahmad96hijazi** [comment]
Uncaught SyntaxError: Unexpected token '>'
Uncaught TypeError: window.ignite is not a function
Uncaught ReferenceError: Ignition is not defined

**Comment by ahmad96hijazi** [comment]
![image](https://user-images.githubusercontent.com/40335765/146594988-fa0cc926-f105-4007-852b-24515c93bd89.png)

**Comment by rubenvanassche** [comment]
I think somehow the JS code of Ignition is getting overwritten, could you share your full HTML code of this page with me please? Then we can take a look

**Comment by ahmad96hijazi** [comment]
https://we.tl/t-ei34VEMfRQ

**Comment by ahmad96hijazi** [comment]
![image](https://user-images.githubusercontent.com/40335765/146810032-e85a1152-2e63-4be3-a3db-eb7b54484cbc.png)
this is my dependencies

**Comment by ahmad96hijazi** [comment]
i am using laravel-page-speed package i activate the remove quotes middleware that make the problem thank you very much for your support
