### ISSUE TITLE
TODO in docs for dark theme screenshot

### ISSUE THREAD

**Issue by brendt** [facade/ignition#50]
<img width="699" alt="Screen Shot 2019-09-02 at 10 02 34" src="https://user-images.githubusercontent.com/6905297/64099397-79c93380-cd69-11e9-9331-a79d58d2ef41.png">

On https://flareapp.io/docs/ignition-for-laravel/configuration#theme-support

**Comment by mpociot** [comment]
@freekmurze can you do this? You took the other screenshots too, so the folders would match

**Comment by shane-smith** [comment]
There's a screenshot here, perhaps the same one can be reused:

https://freek.dev/1441-introducing-ignition#dark-mode

**Comment by freekmurze** [comment]
Fixed.
