### ISSUE TITLE
afterResolving('blade.compiler') Callback not called anymore...

### ISSUE THREAD

**Issue by jjhamkuijpers** [facade/ignition#54]
Some packages like Lab404\Impersonate have a callback for when blade.compiler is resolved but this is not called anymore after installing ignition..

```php
$this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
     // This is not called anymore...
});
```

**Comment by mpociot** [comment]
This one is already fixed. I'll tag a new version to fix this later, as we are going to look at the incoming PRs now.
