### ISSUE TITLE
ContextTab forces HTTPS for gitUrlParse

### ISSUE THREAD

**Issue by axit-joost** [facade/ignition#56]
https://github.com/facade/ignition/blob/5fc04aeea69cabbe37c2c9069a9de2e048400720/resources/js/components/Tabs/ContextTab.vue#L107

This is assuming `https://` for all Git URLs. For folks who run an SCM on-premises (such as GitLab on-prem) behind a firewall or in an otherwise air-gapped environment, SSL certificates may not always be an option.

That being said, not sure what could be a suitable solution, as the original information is a `GitUrl` that is parsed through `git-url-parse`. And since `git@somelocalscm.ad.domain.tld:user/repo.git` does not contain any protocol information to begin with, we need at least something. And assuming SSL makes a lot of sense, so I get it.

Perhaps having a small dropdown in front of the link to select the protocol (`HTTP` or `HTTPS`) once and store it in a cookie or session storage for all subsequent requests? Have it default to HTTPS (which makes sense) or have it configurable in an `.env` environment?

I bet this only affects a small percentage of users. But if you include a means to jump to your IDE in the right file on the right line, users would like to have the same experience when clicking on that Git link, without needing to change `https://` into `http://`

In any case, congratulations on the release. It's already amazing!

**Comment by axit-joost** [comment]
Or simply show two links. One for http, one for https.

**Comment by freekmurze** [comment]
I'm going to leave things as they are for now, as it is recommended to use https for everything.
