### ISSUE TITLE
Ability for runnable solutions to have redirects

### ISSUE THREAD

**Issue by jasonvarga** [facade/ignition#60]
It would be nice if the solution's run button could just redirect to a URL.

For example, we might want to send a user to a page in an admin interface.

I considered opening a PR, but wasn't sure what direction would be most appropriate.
A separate interface (eg. LinkableSolution), allowing a RunnableSolution run's method to return a redirect, or something else entirely.

**Comment by freekmurze** [comment]
`setDocumentationLinks` could be used to inform users they should visit a certain page.

See example on https://flareapp.io/docs/solutions/adding-custom-solutions

**Comment by jasonvarga** [comment]
True, that works. You just don't get the nice action button. That'll do!
