### ISSUE TITLE
Error with file uploads

### ISSUE THREAD

**Issue by MasterRO94** [facade/ignition#61]
Laravel 5.8.14
PHP 7.2
Ubuntu 18.04

After submitting a form with file input and get an exception ignition fails with erorr
`Argument 1 passed to Facade\FlareClient\Context\RequestContext::Facade\FlareClient\Context\{closure}() must be of the type array, object given`

**Comment by mpociot** [comment]
This is already fixed in version 1.0.1 of the flare-client-php dependency. Please update your dependencies
