### ISSUE TITLE
hot reloading is outputting raw javascript  

### ISSUE THREAD

**Issue by stevethomas** [facade/ignition#62]
![image](https://user-images.githubusercontent.com/1127412/64137184-03483680-ce3a-11e9-95f0-3ee962260993.png)
When I run `yarn run hot` or `npm run hot` on a Laravel 5.8 project, it is outputting the javascript to the browser as above.

I tried this on two projects and confirmed removing `:3000` from the url resolved the issue in both cases.

**Comment by rdelafuente** [comment]
#16 

See https://github.com/facade/ignition/issues/16#issuecomment-527260360

**Comment by stevethomas** [comment]
oh my bad, this resolved the issue thanks!
