### ISSUE TITLE
MissingImportSolutionProvider gives a DirectoryNotFoundException if a vendor folder does not exist

### ISSUE THREAD

**Issue by johanvanhelden** [facade/ignition#63]
Our project uses Larastan for static code analysis and that one depends on PHPStan. In the [composer.json](https://github.com/phpstan/phpstan/blob/master/composer.json) PHPStan mentions a build directory, but in the actual folder on my filesystem that one is missing. 

If I remove an import from my controller, I am getting a classic Symphony error page with a ` DirectoryNotFoundException` telling me:
```
 (1/1) DirectoryNotFoundException

The "/var/www/projects/PROJECTNAME/vendor/composer/../phpstan/phpstan/build/PHPStan" directory does not exist.
```

It would be nice if the `MissingImportSolutionProvider` would just ignore **vendor** folders that do not exist. Because now I get an error, unrelated to the actual error and that's really confusing. And we can not fix those missing vendor paths ourselves.

Of course I could ignore this solution provider, but it would be nice if it would "just work" :see_no_evil:

**Comment by freekmurze** [comment]
@johanvanhelden could you submit a PR that fixes this for you?
