### ISSUE TITLE
Support Filling Empty Envs with Quotes

### ISSUE THREAD

**Issue by adrianb93** [facade/ignition#66]
Just wanted to report a bug regarding filling dotenv variables.

**To reproduce:**

I removed my app key and left empty quotes:

```
APP_KEY=''
```

> Side note: I like wrapping my env values in quotes. It looks cleaner in my IDE and in vim's syntax highlighting.

I saw the ignition error page suggestion to fill it in. I clicked the button. The env variable did not insert between the quotes:

```
APP_KEY=base64:qU7L9wham311j3hfFhAH/r+JATuTzLUq2MuLWoT9BJs=''
```

**Expected behaviour:**

It should have filled between the quotes:

```
APP_KEY='base64:qU7L9wham311j3hfFhAH/r+JATuTzLUq2MuLWoT9BJs='
```

... or

```
APP_KEY="base64:qU7L9wham311j3hfFhAH/r+JATuTzLUq2MuLWoT9BJs="
```

**Comment by mpociot** [comment]
This is the same behavior that happens when you run `php artisan key:generate` locally (as that's what the solution does in the background).
So unless Laravel itself supports this, we are not going to make this work.

**Comment by adrianb93** [comment]
Thanks. I'll follow this up 🙂
