### ISSUE TITLE
Wrong lines of code are shown

### ISSUE THREAD

**Issue by klaasgeldof** [facade/ignition#68]
See example in screenshots below: the error is on line 8, but in mail and Slack, the wrong lines are shown. In Flare it's correct. 

I think this is only the case with errors in Blade views, but I'm not sure.

![Schermafbeelding 2019-09-03 om 13 34 31](https://user-images.githubusercontent.com/35819/64170317-2087ff80-ce50-11e9-864c-a94e07fe2c7d.png)
![Schermafbeelding 2019-09-03 om 13 35 31](https://user-images.githubusercontent.com/35819/64170319-2087ff80-ce50-11e9-9979-3a878a62c763.png)
![Schermafbeelding 2019-09-03 om 13 36 16](https://user-images.githubusercontent.com/35819/64170320-2087ff80-ce50-11e9-9a90-2050c0b4dee2.png)

**Comment by freekmurze** [comment]
Hi, I've created a Flare support ticket for this. Closing this issue as this issue tracker is only meant for Ignition issues.
