### ISSUE TITLE
window.ignite is not a function | Ignition is not defined (console errors)

### ISSUE THREAD

**Issue by aFluxx** [facade/ignition#72]
Laravel Framework 5.8.34

After installing ignition and going to a "broken" page, my page looks like:
https://i.gyazo.com/4b927b97c6d6ef60e9dbfd89bb34ccc0.png

I can see the following errors in the console:
Uncaught SyntaxError: Unexpected identifier
19:05:23.947 social:66 Uncaught TypeError: window.ignite is not a function
    at social:66
19:05:23.947 social:69 Uncaught ReferenceError: Ignition is not defined
    at social:69

I've just been following these steps to install:
https://flareapp.io/docs/ignition-for-laravel/installation

Any idea what could be causing this?

**Comment by rdelafuente** [comment]
Hello!

Please see #16

**Comment by aFluxx** [comment]
Correct, I'll try it out. I searched for the error strings in the github log, but bc the other person used a screenshot I got no results. Sorry for the hassle
