### ISSUE TITLE
Rendering of error is broken in Nova.

### ISSUE THREAD

**Issue by mikebronner** [facade/ignition#73]
<img width="1499" alt="Screen Shot 2019-09-03 at 10 12 46 AM" src="https://user-images.githubusercontent.com/1791050/64194199-6387aa00-ce33-11e9-9051-494727318bec.png">

I will see if I can work on a PR for this, if I can get to it, but if you get started before me, please feel free to implement a fix! :)

**Comment by freekmurze** [comment]
Go ahead Mike! 👍 Thank you!

**Comment by freekmurze** [comment]
Closing this for now, as I think this should probably be solved in Nova.
