### ISSUE TITLE
Font broken problem in error page

### ISSUE THREAD

**Issue by ravenKaisar** [facade/ignition#74]
Laravel error page is awesome! But Can't see the font text

![Screenshot_3](https://user-images.githubusercontent.com/16849877/64195909-72f30b80-cea4-11e9-85ff-572b02f089eb.png)

**Comment by sebastiandedeyne** [comment]
Well that's not useful :D Could you share some more details? Which browser & OS are you on? And what language are they in?

**Comment by ravenKaisar** [comment]
OS: Windows 7
PHP: 7.2
Browser: Google Chrome
Font: Segoe UI

Fresh install Laravel 6.0. After installing, the application has run perfectly. Then checking the error page, I see that the font is broken

**Comment by willemvb** [comment]
Sorry, but we cannot reproduce at this point.

- What language is your OS?
- What language is your browser?

Is Segoe UI the font actually in use when you inspect a text node? Can you inspect and check the 'Rendered fonts' section at the bottom right of the inspector to be sure?

![Screen Shot 2019-09-04 at 15 04 08](https://user-images.githubusercontent.com/1336390/64257341-80040f00-cf25-11e9-86e6-0206acc57ff5.png)

**Comment by ravenKaisar** [comment]
Inter & Segeo UI Semibold font seen this picture

![Screenshot_17](https://user-images.githubusercontent.com/16849877/64282047-532c1800-cf76-11e9-8719-d5f23cf846a4.png)

**Comment by willemvb** [comment]
Ok @ravenKaisar, thank you for the additional info! 
Can you try one more thing?

In the `body` section of the 'Styles', `Inter` is the first font in the font stack. 
Can you try and remove `Inter` from the font stack, so it starts with `-apple-system, …` and see if this helps?

![Screen Shot 2019-09-05 at 09 10 17](https://user-images.githubusercontent.com/1336390/64319727-55659500-cfbd-11e9-9158-c56c4a00d390.png)

**Comment by ravenKaisar** [comment]
Removing `Inter` font is working just fine. Again refreshed, the problem persists. How do I make a Permanent Solution?

**Comment by willemvb** [comment]
Should be fixed in the latest release: https://github.com/facade/ignition/releases

**Comment by ravenKaisar** [comment]
thanks @willemvb for your PR

**Comment by LucaRed** [comment]
I found the problem. There's [a symbol font with the same name](http://legionfonts.com/fonts/inter-regular).

Inter is a very beautiful font. I think that we could safely add it back by ensuring to actually load it from their CDN.

**Comment by willemvb** [comment]
Hi @LucaRed,

Thanks for the further investigation! Inter is indeed a very fine font. We had the same feeling that there was some other font installed locally in this case, so removed it to avoid further problems.

Furthermore, we also removed other external resources from Ignition ever since (see #134), so we're not planning on introducing new resources at this point.

**Comment by rsms** [comment]
Is it possible you used the `local()` directive in `@font-face` declarations? `local()` should never be used in production for the very reason witnessed here as it may cause arbitrary fonts to be loaded for different users :–)
