### ISSUE TITLE
Add better error messages for missing validation rules.

### ISSUE THREAD

**Issue by hailwood** [facade/ignition#79]
Right now if we use an invalid validation rule we get something that is helpful enough.
![image](https://user-images.githubusercontent.com/709773/64217354-31e51080-cf11-11e9-88a9-3c8ab561ca1e.png)

We can do better
![image](https://user-images.githubusercontent.com/709773/64217548-ed0da980-cf11-11e9-92fd-24c6c0491a1a.png)

This should take into account any of the `validateX` functions on the Validator class and any array keys in the `$extensions` public property.

**Comment by krisnaw** [comment]
Hey, if not in rush, I'd like to take this 😀

**Comment by freekmurze** [comment]
This has been taken care off.
