### ISSUE TITLE
detecting an Accept of application/json and returning JSON only

### ISSUE THREAD

**Issue by acidjazz** [facade/ignition#80]
This would help debugging greatly since I could have something like an axios middleware properly detect this and then parse/display/report accordingly. Saving time going through devtools/logs/etc

**Comment by freekmurze** [comment]
I don't fully understand your proposal. Could you give a concrete situation where an exception would be thrown where we could add a solution for?

**Comment by mpociot** [comment]
@freekmurze from my understanding the proposal is to not return an HTML view, when a request throws an exception that has an `application/json` Accept header.
But instead, we could return the JSON version of our report object.

**Comment by freekmurze** [comment]
Got it, thanks for clarifying.

**Comment by freekmurze** [comment]
Seem like there no HTML returned when requesting json:  https://github.com/facade/ignition/pull/127/files#diff-f636f7f56789a0252ec5833b6c8c5dccR40

**Comment by acidjazz** [comment]
@freekmurze @mpociot i'm actually still finding a lot of situations where ignition is returning HTML/VUE source and not JSON, if you'd like to re-open this I can work on a concrete example

**Comment by freekmurze** [comment]
I'll reopen this as soon as you post a few concrete examples. Feel free to PR them as failing tests. You're a hero if you would PR tests and a solution for this :-)

**Comment by acidjazz** [comment]
@freekmurze as soon as i find the time!
