### ISSUE TITLE
Solution parameters are not passed when executing solutions

### ISSUE THREAD

**Issue by jerodev** [facade/ignition#85]
When creating a [`RunnableSolution`](https://github.com/facade/ignition-contracts/blob/master/src/RunnableSolution.php) with constructor parameters, Ignition always throws an error when trying to run the solution because the solution is being resolved using the container without adding parameters.

https://github.com/facade/ignition/blob/cf7364d2598a6b36be492e7cd10dcf1b3c375a09/src/SolutionProviders/SolutionProviderRepository.php#L84

    local.ERROR: Unresolvable dependency resolving [Parameter #0 [ <required> string $class ]] in class Facade\Ignition\Solutions\TestSolution {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #0 [ <required> string $class ]] in class Facade\\Ignition\\Solutions\\TestSolution at .../vendor/laravel/framework/src/Illuminate/Container/Container.php:994)

**Comment by mpociot** [comment]
What parameters are you trying to pass to the runnable solution? 
The solution constructor for runnable solutions can be used for dependency injection.

**Comment by jerodev** [comment]
For example, the [`SuggestImportSolution`](https://github.com/facade/ignition/blob/master/src/Solutions/SuggestImportSolution.php) has the missing class name as a constructor parameter.
This solution is not runnable, but there currently are no runnable solutions with constructor parameters.

https://github.com/facade/ignition/blob/8992921a199e9632cb3da76709aff1d53431259a/src/Solutions/SuggestImportSolution.php#L12

**Comment by mpociot** [comment]
Yeah, I don't know if we can come up with a way to make the solutions runnable, allow dependency injections, while still allowing manual constructor parameters.

You could bind your custom runnable solutions to the container yourself to ensure the right parameters get passed to the solution.

Besides that you could make the constructor parameters nullable and use the `getRunParameters` method to pass any data that is required for the solution to run.

See: 
https://github.com/facade/ignition/pull/42/files#diff-82dcb9a3c43869bb3ff83a19e663a24eR12-R17
And
https://github.com/facade/ignition/pull/42/files#diff-82dcb9a3c43869bb3ff83a19e663a24eR44-R51

**Comment by jerodev** [comment]
Oh my, I should have taken a closer look at the documentation. I did not know the parameters were serialized and added to the Solution object before running.

Thank you for the clarification.
