### ISSUE TITLE
Suggested implementation for 5.5+ doesn't work <5.6.13

### ISSUE THREAD

**Issue by devfrey** [facade/ignition#88]
The documentation suggests adding the following method for getting Ignition to work on 5.5, 5.6, 5.7, and some versions of 5.8:

```php
protected function whoopsHandler()
{
    try {
        return app(\Whoops\Handler\HandlerInterface::class);
    } catch (\Illuminate\Contracts\Container\BindingResolutionException $e) {
        return (new \Illuminate\Foundation\Exceptions\WhoopsHandler)->forDebug();
    }
}
```

However, the `WhoopsHandler` wasn't introduced until 5.6.13. So this solution doesn't always work. Perhaps add a small reference to the doc that the fallback doesn't work <5.6.13?

**Comment by mpociot** [comment]
Thank you! Could you send a PR to the documentation at https://github.com/facade/flare-docs/blob/master/docs/ignition-for-laravel/installation.md ?

**Comment by devfrey** [comment]
@mpociot Done!

**Comment by mpociot** [comment]
Thank you! :)
