### ISSUE TITLE
Problem with open_basedir restriction

### ISSUE THREAD

**Issue by acodingproject** [facade/ignition#90]
I got the following error from IncorrectValetDbCredentialsSolutionProvider.php line 60:

file_exists(): open_basedir restriction in effect. File(/usr/local/bin/valet) is not within the allowed path(s)

**Comment by mpociot** [comment]
Thank you for reporting this. We are now wrapping the lookup of the solution providers in a try-catch block, so this error should be gone in version 1.4.10
