### ISSUE TITLE
Undefined Offset error when stack trace is not found

### ISSUE THREAD

**Issue by abishekrsrikaanth** [facade/ignition#92]
First of all loving your work. I am seeing a lot of information that helps with debugging errors.

I just created a new laravel 6 project and added a master layout and extended it to a page. The page is available here for reference https://gist.github.com/abishekrsrikaanth/5daeb5469c4d065780c23a338e39c49c.

I receive this error https://flareapp.io/share/k47q9x7W#F47 when running the page and it looks like ignition is throwing an error because the underlying app is not providing a stack trace to ignition.

**Comment by abishekrsrikaanth** [comment]
@mpociot any reason why this was closed?

**Comment by freekmurze** [comment]
Because it was fixed (see this commit https://github.com/facade/ignition/commit/f5ec5c78db2c084eecd67ad4a43ca9a1e87f53b7)
